// @generated from crates/abrase-cli/tests/fixtures/core_heap.abe — do not edit.
// Trust archive: the abrase-written heap, AOT-compiled to no_std Rust.
// Regenerate: `cargo test -p abrase-cli --test core_gen_tests regenerate -- --ignored`.
#![allow(dead_code, unused, unused_parens)]
// generated by polka-rustc (core backend)

fn core_peek(arena: &[u8], addr: u64, width: u64) -> Result<u64, &'static str> {
    if addr & (width - 1) != 0 { return Err("core: misaligned access"); }
    let end = match addr.checked_add(width) { Some(e) => e, None => return Err("core: address overflow") };
    if end > arena.len() as u64 { return Err("core: out-of-bounds access"); }
    let mut v: u64 = 0;
    let mut i = 0u64;
    while i < width { v |= (arena[(addr + i) as usize] as u64) << (8 * i); i += 1; }
    Ok(v)
}
fn core_poke(arena: &mut [u8], addr: u64, val: u64, width: u64) -> Result<(), &'static str> {
    if addr & (width - 1) != 0 { return Err("core: misaligned access"); }
    let end = match addr.checked_add(width) { Some(e) => e, None => return Err("core: address overflow") };
    if end > arena.len() as u64 { return Err("core: out-of-bounds access"); }
    let mut i = 0u64;
    while i < width { arena[(addr + i) as usize] = (val >> (8 * i)) as u8; i += 1; }
    Ok(())
}
fn f38(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    r0 = a[0];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r1 = 0; pc = 1; }
        1 => { r2 = r1; r1 = u64::MAX; pc = 2; }
        2 => { r3 = r0; pc = 3; }
        3 => { pc = 4; }
        4 => { r1 = r2.wrapping_add(r3); pc = 5; }
        5 => { return Ok(r1); }
        _ => return Ok(r0),
    } }
}
fn f39(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    r0 = a[0];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r1 = (r0 as i64).wrapping_add(63) as u64; pc = 1; }
        1 => { r2 = 64u64; pc = 2; }
        2 => { r3 = match (r1 as i64).checked_div(r2 as i64) { Some(v) => v as u64, None => return Err("div by zero") }; pc = 3; }
        3 => { return Ok(r3); }
        _ => return Ok(r0),
    } }
}
fn f40(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    r0 = a[0];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r1 = 24u64; pc = 1; }
        1 => { r9 = r0; pc = 2; }
        2 => { r2 = f39(arena, &[r9])?; pc = 3; }
        3 => { r3 = 8u64; pc = 4; }
        4 => { r4 = (r2 as i64).wrapping_mul(r3 as i64) as u64; pc = 5; }
        5 => { r5 = (r1 as i64).wrapping_add(r4 as i64) as u64; pc = 6; }
        6 => { r6 = 8u64; pc = 7; }
        7 => { r7 = (r0 as i64).wrapping_mul(r6 as i64) as u64; pc = 8; }
        8 => { r8 = (r5 as i64).wrapping_add(r7 as i64) as u64; pc = 9; }
        9 => { return Ok(r8); }
        _ => return Ok(r0),
    } }
}
fn f41(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r2 = 24u64; pc = 1; }
        1 => { r3 = (r0 as i64).wrapping_add(r2 as i64) as u64; pc = 2; }
        2 => { r8 = r1; pc = 3; }
        3 => { r4 = f39(arena, &[r8])?; pc = 4; }
        4 => { r5 = 8u64; pc = 5; }
        5 => { r6 = (r4 as i64).wrapping_mul(r5 as i64) as u64; pc = 6; }
        6 => { r7 = (r3 as i64).wrapping_add(r6 as i64) as u64; pc = 7; }
        7 => { return Ok(r7); }
        _ => return Ok(r0),
    } }
}
fn f42(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r2 = 24u64; pc = 1; }
        1 => { r3 = (r0 as i64).wrapping_shl((r2 as u32) & 63) as u64; pc = 2; }
        2 => { r4 = 16777215u64; pc = 3; }
        3 => { r5 = r1 & r4; pc = 4; }
        4 => { r6 = r3 | r5; pc = 5; }
        5 => { return Ok(r6); }
        _ => return Ok(r0),
    } }
}
fn f43(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    r0 = a[0];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r1 = 24u64; pc = 1; }
        1 => { r2 = (r0 as i64).wrapping_shr((r1 as u32) & 63) as u64; pc = 2; }
        2 => { return Ok(r2); }
        _ => return Ok(r0),
    } }
}
fn f44(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    r0 = a[0];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r13 = r0; pc = 1; }
        1 => { r1 = f43(arena, &[r13])?; pc = 2; }
        2 => { r2 = 32u64; pc = 3; }
        3 => { r3 = if (r1 as i64) < (r2 as i64) { 1 } else { 0 }; pc = 4; }
        4 => { if r3 == 0 { pc = 7; } else { pc = 5; } }
        5 => { r4 = 18446744073709551615u64; pc = 6; }
        6 => { pc = 25; }
        7 => { r5 = (r1 as i64).wrapping_add(4) as u64; pc = 8; }
        8 => { r13 = r5; r5 = u64::MAX; pc = 9; }
        9 => { r5 = f38(arena, &[r13])?; pc = 10; }
        10 => { r13 = r5; r5 = u64::MAX; pc = 11; }
        11 => { pc = 12; }
        12 => { r5 = core_peek(arena, r13, 4)?; pc = 13; }
        13 => { r6 = 16777215u64; pc = 14; }
        14 => { r7 = r5 & r6; pc = 15; }
        15 => { r8 = 16777215u64; pc = 16; }
        16 => { r9 = r0 & r8; pc = 17; }
        17 => { r10 = if (r7 as i64) != (r9 as i64) { 1 } else { 0 }; pc = 18; }
        18 => { if r10 == 0 { pc = 21; } else { pc = 19; } }
        19 => { r11 = 18446744073709551615u64; pc = 20; }
        20 => { pc = 22; }
        21 => { r11 = r1; pc = 22; }
        22 => { r4 = r11; pc = 23; }
        23 => { pc = 24; }
        24 => { pc = 25; }
        25 => { return Ok(r4); }
        _ => return Ok(r0),
    } }
}
fn f45(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r2 = 24u64; pc = 1; }
        1 => { r3 = (r0 as i64).wrapping_add(r2 as i64) as u64; pc = 2; }
        2 => { r4 = 64u64; pc = 3; }
        3 => { r5 = match (r1 as i64).checked_div(r4 as i64) { Some(v) => v as u64, None => return Err("div by zero") }; pc = 4; }
        4 => { r6 = 8u64; pc = 5; }
        5 => { r7 = (r5 as i64).wrapping_mul(r6 as i64) as u64; pc = 6; }
        6 => { r8 = (r3 as i64).wrapping_add(r7 as i64) as u64; pc = 7; }
        7 => { return Ok(r8); }
        _ => return Ok(r0),
    } }
}
fn f46(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r8 = r0; pc = 1; }
        1 => { r9 = r1; pc = 2; }
        2 => { r2 = f45(arena, &[r8, r9])?; pc = 3; }
        3 => { r8 = r2; r2 = u64::MAX; pc = 4; }
        4 => { pc = 5; }
        5 => { r2 = f38(arena, &[r8])?; pc = 6; }
        6 => { r8 = r2; r2 = u64::MAX; pc = 7; }
        7 => { pc = 8; }
        8 => { r2 = core_peek(arena, r8, 8)?; pc = 9; }
        9 => { r3 = 63u64; pc = 10; }
        10 => { r4 = r1 & r3; pc = 11; }
        11 => { r5 = (r2 as i64).wrapping_shr((r4 as u32) & 63) as u64; pc = 12; }
        12 => { r6 = 1u64; pc = 13; }
        13 => { r7 = r5 & r6; pc = 14; }
        14 => { return Ok(r7); }
        _ => return Ok(r0),
    } }
}
fn f47(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r10 = r0; pc = 1; }
        1 => { r11 = r1; pc = 2; }
        2 => { r2 = f45(arena, &[r10, r11])?; pc = 3; }
        3 => { r10 = r2; pc = 4; }
        4 => { r3 = f38(arena, &[r10])?; pc = 5; }
        5 => { r10 = r2; pc = 6; }
        6 => { r4 = f38(arena, &[r10])?; pc = 7; }
        7 => { r10 = r4; r4 = u64::MAX; pc = 8; }
        8 => { pc = 9; }
        9 => { r4 = core_peek(arena, r10, 8)?; pc = 10; }
        10 => { r5 = 1u64; pc = 11; }
        11 => { r6 = 63u64; pc = 12; }
        12 => { r7 = r1 & r6; pc = 13; }
        13 => { r8 = (r5 as i64).wrapping_shl((r7 as u32) & 63) as u64; pc = 14; }
        14 => { r9 = r4 | r8; pc = 15; }
        15 => { r10 = r3; r3 = u64::MAX; pc = 16; }
        16 => { r11 = r9; r9 = u64::MAX; pc = 17; }
        17 => { pc = 18; }
        18 => { pc = 19; }
        19 => { core_poke(arena, r10, r11, 8)?; r3 = 0; pc = 20; }
        20 => { return Ok(r3); }
        _ => return Ok(r0),
    } }
}
fn f48(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r13 = r1; pc = 1; }
        1 => { r2 = f39(arena, &[r13])?; pc = 2; }
        2 => { r3 = 0u64; pc = 3; }
        3 => { r4 = 0u64; pc = 4; }
        4 => { r5 = if (r3 as i64) < (r2 as i64) { 1 } else { 0 }; pc = 5; }
        5 => { if r5 == 0 { pc = 27; } else { pc = 6; } }
        6 => { r6 = 0u64; pc = 7; }
        7 => { r7 = 57600u64; pc = 8; }
        8 => { pc = 9; }
        9 => { r8 = 24u64; pc = 10; }
        10 => { r9 = (r0 as i64).wrapping_add(r8 as i64) as u64; pc = 11; }
        11 => { r10 = 8u64; pc = 12; }
        12 => { r11 = (r3 as i64).wrapping_mul(r10 as i64) as u64; pc = 13; }
        13 => { r12 = (r9 as i64).wrapping_add(r11 as i64) as u64; pc = 14; }
        14 => { r13 = r12; r12 = u64::MAX; pc = 15; }
        15 => { r8 = f38(arena, &[r13])?; pc = 16; }
        16 => { r9 = 0u64; pc = 17; }
        17 => { r13 = r8; r8 = u64::MAX; pc = 18; }
        18 => { r14 = r9; r9 = u64::MAX; pc = 19; }
        19 => { pc = 20; }
        20 => { core_poke(arena, r13, r14, 8)?; r8 = 0; pc = 21; }
        21 => { pc = 22; }
        22 => { r3 = (r3 as i64).wrapping_add(1) as u64; pc = 23; }
        23 => { r8 = 0u64; pc = 24; }
        24 => { r9 = 57601u64; pc = 25; }
        25 => { pc = 26; }
        26 => { pc = 4; }
        27 => { return Ok(r4); }
        _ => return Ok(r0),
    } }
}
fn f49(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r11 = r0; pc = 1; }
        1 => { r12 = r1; pc = 2; }
        2 => { r2 = f41(arena, &[r11, r12])?; pc = 3; }
        3 => { r3 = 0u64; pc = 4; }
        4 => { r4 = 0u64; pc = 5; }
        5 => { r5 = if (r3 as i64) < (r1 as i64) { 1 } else { 0 }; pc = 6; }
        6 => { if r5 == 0 { pc = 26; } else { pc = 7; } }
        7 => { r6 = 0u64; pc = 8; }
        8 => { r7 = 57600u64; pc = 9; }
        9 => { pc = 10; }
        10 => { r8 = 8u64; pc = 11; }
        11 => { r9 = (r3 as i64).wrapping_mul(r8 as i64) as u64; pc = 12; }
        12 => { r10 = (r2 as i64).wrapping_add(r9 as i64) as u64; pc = 13; }
        13 => { r11 = r10; r10 = u64::MAX; pc = 14; }
        14 => { r8 = f38(arena, &[r11])?; pc = 15; }
        15 => { r9 = 0u64; pc = 16; }
        16 => { r11 = r8; r8 = u64::MAX; pc = 17; }
        17 => { r12 = r9; r9 = u64::MAX; pc = 18; }
        18 => { pc = 19; }
        19 => { core_poke(arena, r11, r12, 8)?; r8 = 0; pc = 20; }
        20 => { pc = 21; }
        21 => { r3 = (r3 as i64).wrapping_add(1) as u64; pc = 22; }
        22 => { r8 = 0u64; pc = 23; }
        23 => { r9 = 57601u64; pc = 24; }
        24 => { pc = 25; }
        25 => { pc = 5; }
        26 => { return Ok(r4); }
        _ => return Ok(r0),
    } }
}
fn f50(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r4 = r0; pc = 1; }
        1 => { r2 = f38(arena, &[r4])?; pc = 2; }
        2 => { r3 = 1u64; pc = 3; }
        3 => { r4 = r2; r2 = u64::MAX; pc = 4; }
        4 => { r5 = r3; r3 = u64::MAX; pc = 5; }
        5 => { pc = 6; }
        6 => { core_poke(arena, r4, r5, 4)?; r2 = 0; pc = 7; }
        7 => { pc = 8; }
        8 => { r4 = r0; pc = 9; }
        9 => { r5 = r1; pc = 10; }
        10 => { r2 = f48(arena, &[r4, r5])?; pc = 11; }
        11 => { pc = 12; }
        12 => { r4 = r0; pc = 13; }
        13 => { r5 = r1; pc = 14; }
        14 => { r2 = f49(arena, &[r4, r5])?; pc = 15; }
        15 => { return Ok(r2); }
        _ => return Ok(r0),
    } }
}
fn f51(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    r0 = a[0];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r1 = 0u64; pc = 1; }
        1 => { r3 = r1; pc = 2; }
        2 => { r1 = f38(arena, &[r3])?; pc = 3; }
        3 => { r2 = 32u64; pc = 4; }
        4 => { r3 = r1; r1 = u64::MAX; pc = 5; }
        5 => { r4 = r2; pc = 6; }
        6 => { pc = 7; }
        7 => { core_poke(arena, r3, r4, 8)?; r1 = 0; pc = 8; }
        8 => { pc = 9; }
        9 => { r1 = 8u64; pc = 10; }
        10 => { r3 = r1; pc = 11; }
        11 => { r1 = f38(arena, &[r3])?; pc = 12; }
        12 => { r3 = r1; r1 = u64::MAX; pc = 13; }
        13 => { r4 = r0; pc = 14; }
        14 => { pc = 15; }
        15 => { core_poke(arena, r3, r4, 8)?; r1 = 0; pc = 16; }
        16 => { pc = 17; }
        17 => { r1 = 16u64; pc = 18; }
        18 => { r3 = r1; pc = 19; }
        19 => { r1 = f38(arena, &[r3])?; pc = 20; }
        20 => { r2 = 0u64; pc = 21; }
        21 => { r3 = r1; r1 = u64::MAX; pc = 22; }
        22 => { r4 = r2; r2 = u64::MAX; pc = 23; }
        23 => { pc = 24; }
        24 => { core_poke(arena, r3, r4, 8)?; r1 = 0; pc = 25; }
        25 => { return Ok(r1); }
        _ => return Ok(r0),
    } }
}
fn f52(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    r0 = a[0];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r1 = 0u64; pc = 1; }
        1 => { r9 = r1; pc = 2; }
        2 => { r1 = f38(arena, &[r9])?; pc = 3; }
        3 => { r9 = r1; r1 = u64::MAX; pc = 4; }
        4 => { pc = 5; }
        5 => { r1 = core_peek(arena, r9, 8)?; pc = 6; }
        6 => { r9 = r0; pc = 7; }
        7 => { r2 = f40(arena, &[r9])?; pc = 8; }
        8 => { r3 = 8u64; pc = 9; }
        9 => { r9 = r3; pc = 10; }
        10 => { r3 = f38(arena, &[r9])?; pc = 11; }
        11 => { r9 = r3; r3 = u64::MAX; pc = 12; }
        12 => { pc = 13; }
        13 => { r3 = core_peek(arena, r9, 8)?; pc = 14; }
        14 => { r4 = (r1 as i64).wrapping_add(r2 as i64) as u64; pc = 15; }
        15 => { r5 = if (r4 as i64) > (r3 as i64) { 1 } else { 0 }; pc = 16; }
        16 => { if r5 == 0 { pc = 19; } else { pc = 17; } }
        17 => { r6 = 0u64; pc = 18; }
        18 => { pc = 55; }
        19 => { r7 = (r1 as i64).wrapping_add(4) as u64; pc = 20; }
        20 => { r9 = r7; r7 = u64::MAX; pc = 21; }
        21 => { r7 = f38(arena, &[r9])?; pc = 22; }
        22 => { r8 = 0u64; pc = 23; }
        23 => { r9 = r7; r7 = u64::MAX; pc = 24; }
        24 => { r10 = r8; r8 = u64::MAX; pc = 25; }
        25 => { pc = 26; }
        26 => { core_poke(arena, r9, r10, 4)?; r7 = 0; pc = 27; }
        27 => { pc = 28; }
        28 => { r7 = (r1 as i64).wrapping_add(8) as u64; pc = 29; }
        29 => { r9 = r7; r7 = u64::MAX; pc = 30; }
        30 => { r7 = f38(arena, &[r9])?; pc = 31; }
        31 => { r9 = r7; r7 = u64::MAX; pc = 32; }
        32 => { r10 = r0; pc = 33; }
        33 => { pc = 34; }
        34 => { core_poke(arena, r9, r10, 4)?; r7 = 0; pc = 35; }
        35 => { pc = 36; }
        36 => { r9 = r1; pc = 37; }
        37 => { r10 = r0; pc = 38; }
        38 => { r7 = f50(arena, &[r9, r10])?; pc = 39; }
        39 => { pc = 40; }
        40 => { r7 = 0u64; pc = 41; }
        41 => { r9 = r7; pc = 42; }
        42 => { r7 = f38(arena, &[r9])?; pc = 43; }
        43 => { r8 = (r1 as i64).wrapping_add(r2 as i64) as u64; pc = 44; }
        44 => { r9 = r7; r7 = u64::MAX; pc = 45; }
        45 => { r10 = r8; r8 = u64::MAX; pc = 46; }
        46 => { pc = 47; }
        47 => { core_poke(arena, r9, r10, 8)?; r7 = 0; pc = 48; }
        48 => { pc = 49; }
        49 => { r7 = 0u64; pc = 50; }
        50 => { r9 = r1; pc = 51; }
        51 => { r10 = r7; r7 = u64::MAX; pc = 52; }
        52 => { r7 = f42(arena, &[r9, r10])?; pc = 53; }
        53 => { r6 = r7; pc = 54; }
        54 => { pc = 55; }
        55 => { return Ok(r6); }
        _ => return Ok(r0),
    } }
}
fn f53(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    let mut r45: u64 = 0;
    let mut r46: u64 = 0;
    let mut r47: u64 = 0;
    let mut r48: u64 = 0;
    let mut r49: u64 = 0;
    let mut r50: u64 = 0;
    let mut r51: u64 = 0;
    let mut r52: u64 = 0;
    let mut r53: u64 = 0;
    let mut r54: u64 = 0;
    let mut r55: u64 = 0;
    let mut r56: u64 = 0;
    let mut r57: u64 = 0;
    let mut r58: u64 = 0;
    r0 = a[0];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r1 = 0u64; pc = 1; }
        1 => { r3 = if (r0 as i64) < (r1 as i64) { 1 } else { 0 }; pc = 2; }
        2 => { if r3 != 0 { pc = 5; } else { pc = 3; } }
        3 => { r4 = 268435456u64; pc = 4; }
        4 => { r3 = if (r0 as i64) > (r4 as i64) { 1 } else { 0 }; pc = 5; }
        5 => { if r3 == 0 { pc = 8; } else { pc = 6; } }
        6 => { r6 = 0u64; pc = 7; }
        7 => { pc = 103; }
        8 => { r7 = 18446744073709551615u64; pc = 9; }
        9 => { r8 = 16u64; pc = 10; }
        10 => { r27 = r8; pc = 11; }
        11 => { r8 = f38(arena, &[r27])?; pc = 12; }
        12 => { r27 = r8; r8 = u64::MAX; pc = 13; }
        13 => { pc = 14; }
        14 => { r8 = core_peek(arena, r27, 8)?; pc = 15; }
        15 => { r9 = 18446744073709551615u64; pc = 16; }
        16 => { r10 = 0u64; pc = 17; }
        17 => { r11 = 0u64; pc = 18; }
        18 => { r12 = if (r8 as i64) != (r11 as i64) { 1 } else { 0 }; pc = 19; }
        19 => { if r12 == 0 { pc = 75; } else { pc = 20; } }
        20 => { r13 = 0u64; pc = 21; }
        21 => { r14 = 57600u64; pc = 22; }
        22 => { pc = 23; }
        23 => { r15 = 16u64; pc = 24; }
        24 => { r16 = (r8 as i64).wrapping_add(r15 as i64) as u64; pc = 25; }
        25 => { r27 = r16; r16 = u64::MAX; pc = 26; }
        26 => { r15 = f38(arena, &[r27])?; pc = 27; }
        27 => { r27 = r15; r15 = u64::MAX; pc = 28; }
        28 => { pc = 29; }
        29 => { r15 = core_peek(arena, r27, 8)?; pc = 30; }
        30 => { r16 = 0u64; pc = 31; }
        31 => { r18 = if (r9 as i64) < (r16 as i64) { 1 } else { 0 }; pc = 32; }
        32 => { if r18 == 0 { pc = 40; } else { pc = 33; } }
        33 => { r19 = (r8 as i64).wrapping_add(8) as u64; pc = 34; }
        34 => { r27 = r19; r19 = u64::MAX; pc = 35; }
        35 => { r19 = f38(arena, &[r27])?; pc = 36; }
        36 => { r27 = r19; r19 = u64::MAX; pc = 37; }
        37 => { pc = 38; }
        38 => { r19 = core_peek(arena, r27, 4)?; pc = 39; }
        39 => { r18 = if (r19 as i64) == (r0 as i64) { 1 } else { 0 }; pc = 40; }
        40 => { if r18 == 0 { pc = 68; } else { pc = 41; } }
        41 => { r22 = 0u64; pc = 42; }
        42 => { r23 = if (r7 as i64) < (r22 as i64) { 1 } else { 0 }; pc = 43; }
        43 => { if r23 == 0 { pc = 54; } else { pc = 44; } }
        44 => { r25 = 16u64; pc = 45; }
        45 => { r27 = r25; pc = 46; }
        46 => { r25 = f38(arena, &[r27])?; pc = 47; }
        47 => { r27 = r25; r25 = u64::MAX; pc = 48; }
        48 => { r28 = r15; pc = 49; }
        49 => { pc = 50; }
        50 => { core_poke(arena, r27, r28, 8)?; r25 = 0; pc = 51; }
        51 => { pc = 52; }
        52 => { r24 = 0u64; pc = 53; }
        53 => { pc = 64; }
        54 => { r25 = 16u64; pc = 55; }
        55 => { r26 = (r7 as i64).wrapping_add(r25 as i64) as u64; pc = 56; }
        56 => { r27 = r26; r26 = u64::MAX; pc = 57; }
        57 => { r25 = f38(arena, &[r27])?; pc = 58; }
        58 => { r27 = r25; r25 = u64::MAX; pc = 59; }
        59 => { r28 = r15; pc = 60; }
        60 => { pc = 61; }
        61 => { core_poke(arena, r27, r28, 8)?; r25 = 0; pc = 62; }
        62 => { pc = 63; }
        63 => { r24 = 0u64; pc = 64; }
        64 => { r9 = r8; pc = 65; }
        65 => { r8 = 0u64; pc = 66; }
        66 => { r21 = 0u64; pc = 67; }
        67 => { pc = 71; }
        68 => { r7 = r8; pc = 69; }
        69 => { r8 = r15; pc = 70; }
        70 => { r21 = 0u64; pc = 71; }
        71 => { r22 = 0u64; pc = 72; }
        72 => { r23 = 57601u64; pc = 73; }
        73 => { pc = 74; }
        74 => { pc = 17; }
        75 => { r10 = 0u64; pc = 76; }
        76 => { r11 = if (r9 as i64) < (r10 as i64) { 1 } else { 0 }; pc = 77; }
        77 => { if r11 == 0 { pc = 83; } else { pc = 78; } }
        78 => { r27 = r0; pc = 79; }
        79 => { r13 = f52(arena, &[r27])?; pc = 80; }
        80 => { r12 = r13; pc = 81; }
        81 => { pc = 82; }
        82 => { pc = 99; }
        83 => { r27 = r9; pc = 84; }
        84 => { r28 = r0; pc = 85; }
        85 => { r13 = f50(arena, &[r27, r28])?; pc = 86; }
        86 => { pc = 87; }
        87 => { r13 = (r9 as i64).wrapping_add(4) as u64; pc = 88; }
        88 => { r27 = r13; r13 = u64::MAX; pc = 89; }
        89 => { r13 = f38(arena, &[r27])?; pc = 90; }
        90 => { r27 = r13; r13 = u64::MAX; pc = 91; }
        91 => { pc = 92; }
        92 => { r13 = core_peek(arena, r27, 4)?; pc = 93; }
        93 => { r27 = r9; pc = 94; }
        94 => { r28 = r13; r13 = u64::MAX; pc = 95; }
        95 => { pc = 96; }
        96 => { r13 = f42(arena, &[r27, r28])?; pc = 97; }
        97 => { r12 = r13; pc = 98; }
        98 => { pc = 99; }
        99 => { r6 = r12; pc = 100; }
        100 => { pc = 101; }
        101 => { pc = 102; }
        102 => { pc = 103; }
        103 => { return Ok(r6); }
        _ => return Ok(r0),
    } }
}
fn f54(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    let mut r45: u64 = 0;
    let mut r46: u64 = 0;
    r0 = a[0];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r1 = (r0 as i64).wrapping_add(8) as u64; pc = 1; }
        1 => { r15 = r1; r1 = u64::MAX; pc = 2; }
        2 => { r1 = f38(arena, &[r15])?; pc = 3; }
        3 => { r15 = r1; r1 = u64::MAX; pc = 4; }
        4 => { pc = 5; }
        5 => { r1 = core_peek(arena, r15, 4)?; pc = 6; }
        6 => { r2 = 0u64; pc = 7; }
        7 => { r3 = 0u64; pc = 8; }
        8 => { r4 = if (r2 as i64) < (r1 as i64) { 1 } else { 0 }; pc = 9; }
        9 => { if r4 == 0 { pc = 44; } else { pc = 10; } }
        10 => { r5 = 0u64; pc = 11; }
        11 => { r6 = 57600u64; pc = 12; }
        12 => { pc = 13; }
        13 => { r15 = r0; pc = 14; }
        14 => { r16 = r2; pc = 15; }
        15 => { r7 = f46(arena, &[r15, r16])?; pc = 16; }
        16 => { r8 = 1u64; pc = 17; }
        17 => { r9 = if (r7 as i64) == (r8 as i64) { 1 } else { 0 }; pc = 18; }
        18 => { if r9 == 0 { pc = 37; } else { pc = 19; } }
        19 => { r15 = r0; pc = 20; }
        20 => { r16 = r1; pc = 21; }
        21 => { r11 = f41(arena, &[r15, r16])?; pc = 22; }
        22 => { r12 = 8u64; pc = 23; }
        23 => { r13 = (r2 as i64).wrapping_mul(r12 as i64) as u64; pc = 24; }
        24 => { r14 = (r11 as i64).wrapping_add(r13 as i64) as u64; pc = 25; }
        25 => { r15 = r14; r14 = u64::MAX; pc = 26; }
        26 => { pc = 27; }
        27 => { r11 = f38(arena, &[r15])?; pc = 28; }
        28 => { r15 = r11; r11 = u64::MAX; pc = 29; }
        29 => { pc = 30; }
        30 => { r11 = core_peek(arena, r15, 8)?; pc = 31; }
        31 => { r15 = r11; r11 = u64::MAX; pc = 32; }
        32 => { pc = 33; }
        33 => { r11 = f59(arena, &[r15])?; pc = 34; }
        34 => { pc = 35; }
        35 => { r10 = 0u64; pc = 36; }
        36 => { pc = 38; }
        37 => { r10 = 0u64; pc = 38; }
        38 => { pc = 39; }
        39 => { r2 = (r2 as i64).wrapping_add(1) as u64; pc = 40; }
        40 => { r7 = 0u64; pc = 41; }
        41 => { r8 = 57601u64; pc = 42; }
        42 => { pc = 43; }
        43 => { pc = 8; }
        44 => { r3 = (r0 as i64).wrapping_add(4) as u64; pc = 45; }
        45 => { r15 = r3; r3 = u64::MAX; pc = 46; }
        46 => { r3 = f38(arena, &[r15])?; pc = 47; }
        47 => { r4 = (r0 as i64).wrapping_add(4) as u64; pc = 48; }
        48 => { r15 = r4; r4 = u64::MAX; pc = 49; }
        49 => { r4 = f38(arena, &[r15])?; pc = 50; }
        50 => { r15 = r4; r4 = u64::MAX; pc = 51; }
        51 => { pc = 52; }
        52 => { r4 = core_peek(arena, r15, 4)?; pc = 53; }
        53 => { r5 = (r4 as i64).wrapping_add(1) as u64; pc = 54; }
        54 => { r15 = r3; r3 = u64::MAX; pc = 55; }
        55 => { r16 = r5; r5 = u64::MAX; pc = 56; }
        56 => { pc = 57; }
        57 => { pc = 58; }
        58 => { core_poke(arena, r15, r16, 4)?; r3 = 0; pc = 59; }
        59 => { pc = 60; }
        60 => { r3 = 16u64; pc = 61; }
        61 => { r15 = r3; pc = 62; }
        62 => { r3 = f38(arena, &[r15])?; pc = 63; }
        63 => { r15 = r3; r3 = u64::MAX; pc = 64; }
        64 => { pc = 65; }
        65 => { r3 = core_peek(arena, r15, 8)?; pc = 66; }
        66 => { r4 = 16u64; pc = 67; }
        67 => { r5 = (r0 as i64).wrapping_add(r4 as i64) as u64; pc = 68; }
        68 => { r15 = r5; r5 = u64::MAX; pc = 69; }
        69 => { r4 = f38(arena, &[r15])?; pc = 70; }
        70 => { r15 = r4; r4 = u64::MAX; pc = 71; }
        71 => { r16 = r3; pc = 72; }
        72 => { pc = 73; }
        73 => { core_poke(arena, r15, r16, 8)?; r4 = 0; pc = 74; }
        74 => { pc = 75; }
        75 => { r4 = 16u64; pc = 76; }
        76 => { r15 = r4; pc = 77; }
        77 => { r4 = f38(arena, &[r15])?; pc = 78; }
        78 => { r15 = r4; r4 = u64::MAX; pc = 79; }
        79 => { r16 = r0; pc = 80; }
        80 => { pc = 81; }
        81 => { core_poke(arena, r15, r16, 8)?; r4 = 0; pc = 82; }
        82 => { return Ok(r4); }
        _ => return Ok(r0),
    } }
}
fn f55(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    let mut r45: u64 = 0;
    let mut r46: u64 = 0;
    let mut r47: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r16 = r0; pc = 1; }
        1 => { r2 = f44(arena, &[r16])?; pc = 2; }
        2 => { r3 = 0u64; pc = 3; }
        3 => { r4 = if (r2 as i64) < (r3 as i64) { 1 } else { 0 }; pc = 4; }
        4 => { if r4 == 0 { pc = 7; } else { pc = 5; } }
        5 => { r5 = 18446744073709551615u64; pc = 6; }
        6 => { pc = 37; }
        7 => { r6 = (r2 as i64).wrapping_add(8) as u64; pc = 8; }
        8 => { r16 = r6; r6 = u64::MAX; pc = 9; }
        9 => { r6 = f38(arena, &[r16])?; pc = 10; }
        10 => { r16 = r6; r6 = u64::MAX; pc = 11; }
        11 => { pc = 12; }
        12 => { r6 = core_peek(arena, r16, 4)?; pc = 13; }
        13 => { r7 = 0u64; pc = 14; }
        14 => { r9 = if (r1 as i64) < (r7 as i64) { 1 } else { 0 }; pc = 15; }
        15 => { if r9 != 0 { pc = 17; } else { pc = 16; } }
        16 => { r9 = if (r1 as i64) >= (r6 as i64) { 1 } else { 0 }; pc = 17; }
        17 => { if r9 == 0 { pc = 20; } else { pc = 18; } }
        18 => { r11 = 18446744073709551615u64; pc = 19; }
        19 => { pc = 34; }
        20 => { r16 = r2; pc = 21; }
        21 => { r17 = r6; pc = 22; }
        22 => { r12 = f41(arena, &[r16, r17])?; pc = 23; }
        23 => { r13 = 8u64; pc = 24; }
        24 => { r14 = (r1 as i64).wrapping_mul(r13 as i64) as u64; pc = 25; }
        25 => { r15 = (r12 as i64).wrapping_add(r14 as i64) as u64; pc = 26; }
        26 => { r16 = r15; r15 = u64::MAX; pc = 27; }
        27 => { pc = 28; }
        28 => { r12 = f38(arena, &[r16])?; pc = 29; }
        29 => { r16 = r12; r12 = u64::MAX; pc = 30; }
        30 => { pc = 31; }
        31 => { r12 = core_peek(arena, r16, 8)?; pc = 32; }
        32 => { r11 = r12; pc = 33; }
        33 => { pc = 34; }
        34 => { r5 = r11; pc = 35; }
        35 => { pc = 36; }
        36 => { pc = 37; }
        37 => { return Ok(r5); }
        _ => return Ok(r0),
    } }
}
fn f56(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    let mut r45: u64 = 0;
    let mut r46: u64 = 0;
    let mut r47: u64 = 0;
    let mut r48: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    r2 = a[2];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r17 = r0; pc = 1; }
        1 => { r3 = f44(arena, &[r17])?; pc = 2; }
        2 => { r4 = 0u64; pc = 3; }
        3 => { r5 = if (r3 as i64) < (r4 as i64) { 1 } else { 0 }; pc = 4; }
        4 => { if r5 == 0 { pc = 7; } else { pc = 5; } }
        5 => { r6 = 18446744073709551615u64; pc = 6; }
        6 => { pc = 37; }
        7 => { r7 = (r3 as i64).wrapping_add(8) as u64; pc = 8; }
        8 => { r17 = r7; r7 = u64::MAX; pc = 9; }
        9 => { r7 = f38(arena, &[r17])?; pc = 10; }
        10 => { r17 = r7; r7 = u64::MAX; pc = 11; }
        11 => { pc = 12; }
        12 => { r7 = core_peek(arena, r17, 4)?; pc = 13; }
        13 => { r8 = 0u64; pc = 14; }
        14 => { r10 = if (r1 as i64) < (r8 as i64) { 1 } else { 0 }; pc = 15; }
        15 => { if r10 != 0 { pc = 17; } else { pc = 16; } }
        16 => { r10 = if (r1 as i64) >= (r7 as i64) { 1 } else { 0 }; pc = 17; }
        17 => { if r10 == 0 { pc = 20; } else { pc = 18; } }
        18 => { r12 = 18446744073709551615u64; pc = 19; }
        19 => { pc = 35; }
        20 => { r17 = r3; pc = 21; }
        21 => { r18 = r7; pc = 22; }
        22 => { r13 = f41(arena, &[r17, r18])?; pc = 23; }
        23 => { r14 = 8u64; pc = 24; }
        24 => { r15 = (r1 as i64).wrapping_mul(r14 as i64) as u64; pc = 25; }
        25 => { r16 = (r13 as i64).wrapping_add(r15 as i64) as u64; pc = 26; }
        26 => { r17 = r16; r16 = u64::MAX; pc = 27; }
        27 => { pc = 28; }
        28 => { r13 = f38(arena, &[r17])?; pc = 29; }
        29 => { r17 = r13; r13 = u64::MAX; pc = 30; }
        30 => { r18 = r2; pc = 31; }
        31 => { pc = 32; }
        32 => { core_poke(arena, r17, r18, 8)?; r13 = 0; pc = 33; }
        33 => { pc = 34; }
        34 => { r12 = 0u64; pc = 35; }
        35 => { r6 = r12; pc = 36; }
        36 => { pc = 37; }
        37 => { return Ok(r6); }
        _ => return Ok(r0),
    } }
}
fn f57(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    let mut r45: u64 = 0;
    let mut r46: u64 = 0;
    let mut r47: u64 = 0;
    let mut r48: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    r2 = a[2];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r17 = r0; pc = 1; }
        1 => { r3 = f44(arena, &[r17])?; pc = 2; }
        2 => { r4 = 0u64; pc = 3; }
        3 => { r5 = if (r3 as i64) < (r4 as i64) { 1 } else { 0 }; pc = 4; }
        4 => { if r5 == 0 { pc = 7; } else { pc = 5; } }
        5 => { r6 = 18446744073709551615u64; pc = 6; }
        6 => { pc = 41; }
        7 => { r7 = (r3 as i64).wrapping_add(8) as u64; pc = 8; }
        8 => { r17 = r7; r7 = u64::MAX; pc = 9; }
        9 => { r7 = f38(arena, &[r17])?; pc = 10; }
        10 => { r17 = r7; r7 = u64::MAX; pc = 11; }
        11 => { pc = 12; }
        12 => { r7 = core_peek(arena, r17, 4)?; pc = 13; }
        13 => { r8 = 0u64; pc = 14; }
        14 => { r10 = if (r1 as i64) < (r8 as i64) { 1 } else { 0 }; pc = 15; }
        15 => { if r10 != 0 { pc = 17; } else { pc = 16; } }
        16 => { r10 = if (r1 as i64) >= (r7 as i64) { 1 } else { 0 }; pc = 17; }
        17 => { if r10 == 0 { pc = 20; } else { pc = 18; } }
        18 => { r12 = 18446744073709551615u64; pc = 19; }
        19 => { pc = 39; }
        20 => { r17 = r3; pc = 21; }
        21 => { r18 = r7; pc = 22; }
        22 => { r13 = f41(arena, &[r17, r18])?; pc = 23; }
        23 => { r14 = 8u64; pc = 24; }
        24 => { r15 = (r1 as i64).wrapping_mul(r14 as i64) as u64; pc = 25; }
        25 => { r16 = (r13 as i64).wrapping_add(r15 as i64) as u64; pc = 26; }
        26 => { r17 = r16; r16 = u64::MAX; pc = 27; }
        27 => { pc = 28; }
        28 => { r13 = f38(arena, &[r17])?; pc = 29; }
        29 => { r17 = r13; r13 = u64::MAX; pc = 30; }
        30 => { r18 = r2; pc = 31; }
        31 => { pc = 32; }
        32 => { core_poke(arena, r17, r18, 8)?; r13 = 0; pc = 33; }
        33 => { pc = 34; }
        34 => { r17 = r3; pc = 35; }
        35 => { r18 = r1; pc = 36; }
        36 => { r13 = f47(arena, &[r17, r18])?; pc = 37; }
        37 => { pc = 38; }
        38 => { r12 = 0u64; pc = 39; }
        39 => { r6 = r12; pc = 40; }
        40 => { pc = 41; }
        41 => { return Ok(r6); }
        _ => return Ok(r0),
    } }
}
fn f58(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    r0 = a[0];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r8 = r0; pc = 1; }
        1 => { r1 = f44(arena, &[r8])?; pc = 2; }
        2 => { r2 = 0u64; pc = 3; }
        3 => { r3 = if (r1 as i64) < (r2 as i64) { 1 } else { 0 }; pc = 4; }
        4 => { if r3 == 0 { pc = 7; } else { pc = 5; } }
        5 => { r4 = 18446744073709551615u64; pc = 6; }
        6 => { pc = 22; }
        7 => { r8 = r1; pc = 8; }
        8 => { r5 = f38(arena, &[r8])?; pc = 9; }
        9 => { r8 = r1; pc = 10; }
        10 => { r6 = f38(arena, &[r8])?; pc = 11; }
        11 => { r8 = r6; r6 = u64::MAX; pc = 12; }
        12 => { pc = 13; }
        13 => { r6 = core_peek(arena, r8, 4)?; pc = 14; }
        14 => { r7 = (r6 as i64).wrapping_add(1) as u64; pc = 15; }
        15 => { r8 = r5; r5 = u64::MAX; pc = 16; }
        16 => { r9 = r7; r7 = u64::MAX; pc = 17; }
        17 => { pc = 18; }
        18 => { pc = 19; }
        19 => { core_poke(arena, r8, r9, 4)?; r5 = 0; pc = 20; }
        20 => { pc = 21; }
        21 => { r4 = 0u64; pc = 22; }
        22 => { return Ok(r4); }
        _ => return Ok(r0),
    } }
}
fn f59(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    r0 = a[0];
    let mut pc: usize = 0;
    loop { match pc {
        0 => { r11 = r0; pc = 1; }
        1 => { r1 = f44(arena, &[r11])?; pc = 2; }
        2 => { r2 = 0u64; pc = 3; }
        3 => { r3 = if (r1 as i64) < (r2 as i64) { 1 } else { 0 }; pc = 4; }
        4 => { if r3 == 0 { pc = 7; } else { pc = 5; } }
        5 => { r4 = 18446744073709551615u64; pc = 6; }
        6 => { pc = 31; }
        7 => { r11 = r1; pc = 8; }
        8 => { r5 = f38(arena, &[r11])?; pc = 9; }
        9 => { r11 = r5; r5 = u64::MAX; pc = 10; }
        10 => { pc = 11; }
        11 => { r5 = core_peek(arena, r11, 4)?; pc = 12; }
        12 => { r6 = (r5 as i64).wrapping_sub(1) as u64; pc = 13; }
        13 => { pc = 14; }
        14 => { r11 = r1; pc = 15; }
        15 => { r7 = f38(arena, &[r11])?; pc = 16; }
        16 => { r11 = r7; r7 = u64::MAX; pc = 17; }
        17 => { r12 = r6; pc = 18; }
        18 => { pc = 19; }
        19 => { core_poke(arena, r11, r12, 4)?; r7 = 0; pc = 20; }
        20 => { pc = 21; }
        21 => { r7 = 0u64; pc = 22; }
        22 => { r8 = if (r6 as i64) == (r7 as i64) { 1 } else { 0 }; pc = 23; }
        23 => { if r8 == 0 { pc = 29; } else { pc = 24; } }
        24 => { r11 = r1; pc = 25; }
        25 => { r10 = f54(arena, &[r11])?; pc = 26; }
        26 => { pc = 27; }
        27 => { r9 = 1u64; pc = 28; }
        28 => { pc = 30; }
        29 => { r9 = 0u64; pc = 30; }
        30 => { r4 = r9; pc = 31; }
        31 => { return Ok(r4); }
        _ => return Ok(r0),
    } }
}
pub fn core_init(arena: &mut [u8], a0: u64) -> Result<u64, &'static str> { f51(arena, &[a0]) }
pub fn alloc(arena: &mut [u8], a0: u64) -> Result<u64, &'static str> { f53(arena, &[a0]) }
pub fn cell_get(arena: &mut [u8], a0: u64, a1: u64) -> Result<u64, &'static str> { f55(arena, &[a0, a1]) }
pub fn cell_set(arena: &mut [u8], a0: u64, a1: u64, a2: u64) -> Result<u64, &'static str> { f56(arena, &[a0, a1, a2]) }
pub fn cell_set_child(arena: &mut [u8], a0: u64, a1: u64, a2: u64) -> Result<u64, &'static str> { f57(arena, &[a0, a1, a2]) }
pub fn rc_inc(arena: &mut [u8], a0: u64) -> Result<u64, &'static str> { f58(arena, &[a0]) }
pub fn rc_dec(arena: &mut [u8], a0: u64) -> Result<u64, &'static str> { f59(arena, &[a0]) }
