// @generated from crates/abrase-cli/tests/fixtures/core_heap.abe — do not edit.
// Trust archive: the abrase-written heap, AOT-compiled to no_std Rust.
// Regenerate: `cargo test -p abrase-cli --test core_gen_tests regenerate -- --ignored`.
#![allow(dead_code, unused, unused_parens)]
// generated by polka-rustc (core backend)

fn core_peek(arena: &[u8], addr: u64, width: u64) -> Result<u64, &'static str> {
    if addr & (width - 1) != 0 { return Err("core: misaligned access"); }
    let end = match addr.checked_add(width) { Some(e) => e, None => return Err("core: address overflow") };
    if end > arena.len() as u64 { return Err("core: out-of-bounds access"); }
    let mut v: u64 = 0;
    let mut i = 0u64;
    while i < width { v |= (arena[(addr + i) as usize] as u64) << (8 * i); i += 1; }
    Ok(v)
}
fn core_poke(arena: &mut [u8], addr: u64, val: u64, width: u64) -> Result<(), &'static str> {
    if addr & (width - 1) != 0 { return Err("core: misaligned access"); }
    let end = match addr.checked_add(width) { Some(e) => e, None => return Err("core: address overflow") };
    if end > arena.len() as u64 { return Err("core: out-of-bounds access"); }
    let mut i = 0u64;
    while i < width { arena[(addr + i) as usize] = (val >> (8 * i)) as u8; i += 1; }
    Ok(())
}
fn f41(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    r0 = a[0];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r1 = 0; r2 = r1; r1 = u64::MAX; r3 = r0; r1 = r2.wrapping_add(r3); 
return Ok(r1);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f42(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    r0 = a[0];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r1 = (r0 as i64).wrapping_add(63) as u64; r2 = 64u64; r3 = match (r1 as i64).checked_div(r2 as i64) { Some(v) => v as u64, None => return Err("div by zero") }; 
return Ok(r3);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f43(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    r0 = a[0];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r1 = 24u64; r9 = r0; r2 = f42(arena, &[r9])?; r3 = 8u64; r4 = (r2 as i64).wrapping_mul(r3 as i64) as u64; r5 = (r1 as i64).wrapping_add(r4 as i64) as u64; r6 = 8u64; r7 = (r0 as i64).wrapping_mul(r6 as i64) as u64; r8 = (r5 as i64).wrapping_add(r7 as i64) as u64; 
return Ok(r8);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f44(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r2 = 24u64; r3 = (r0 as i64).wrapping_add(r2 as i64) as u64; r8 = r1; r4 = f42(arena, &[r8])?; r5 = 8u64; r6 = (r4 as i64).wrapping_mul(r5 as i64) as u64; r7 = (r3 as i64).wrapping_add(r6 as i64) as u64; 
return Ok(r7);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f45(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r2 = 24u64; r3 = (r0 as i64).wrapping_shl((r2 as u32) & 63) as u64; r4 = 16777215u64; r5 = r1 & r4; r6 = r3 | r5; 
return Ok(r6);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f46(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    r0 = a[0];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r1 = 24u64; r2 = (r0 as i64).wrapping_shr((r1 as u32) & 63) as u64; 
return Ok(r2);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f47(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    r0 = a[0];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r13 = r0; r1 = f46(arena, &[r13])?; r2 = 32u64; r3 = if (r1 as i64) < (r2 as i64) { 1 } else { 0 }; 
if r3 == 0 { __lbl = 7; } else { __lbl = 5; }
match __lbl {
5 => {
r4 = 18446744073709551615u64; 
__lbl = 25;
}
7 => {
r5 = (r1 as i64).wrapping_add(4) as u64; r13 = r5; r5 = u64::MAX; r5 = f41(arena, &[r13])?; r13 = r5; r5 = u64::MAX; r5 = core_peek(arena, r13, 4)?; r6 = 16777215u64; r7 = r5 & r6; r8 = 16777215u64; r9 = r0 & r8; r10 = if (r7 as i64) != (r9 as i64) { 1 } else { 0 }; 
if r10 == 0 { __lbl = 21; } else { __lbl = 19; }
match __lbl {
19 => {
r11 = 18446744073709551615u64; 
__lbl = 22;
}
21 => {
r11 = r1; 
__lbl = 22;
}
_ => {}
}
r4 = r11; 
__lbl = 25;
}
_ => {}
}

return Ok(r4);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f48(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r2 = 24u64; r3 = (r0 as i64).wrapping_add(r2 as i64) as u64; r4 = 64u64; r5 = match (r1 as i64).checked_div(r4 as i64) { Some(v) => v as u64, None => return Err("div by zero") }; r6 = 8u64; r7 = (r5 as i64).wrapping_mul(r6 as i64) as u64; r8 = (r3 as i64).wrapping_add(r7 as i64) as u64; 
return Ok(r8);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f49(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r8 = r0; r9 = r1; r2 = f48(arena, &[r8, r9])?; r8 = r2; r2 = u64::MAX; r2 = f41(arena, &[r8])?; r8 = r2; r2 = u64::MAX; r2 = core_peek(arena, r8, 8)?; r3 = 63u64; r4 = r1 & r3; r5 = (r2 as i64).wrapping_shr((r4 as u32) & 63) as u64; r6 = 1u64; r7 = r5 & r6; 
return Ok(r7);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f50(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r10 = r0; r11 = r1; r2 = f48(arena, &[r10, r11])?; r10 = r2; r3 = f41(arena, &[r10])?; r10 = r2; r4 = f41(arena, &[r10])?; r10 = r4; r4 = u64::MAX; r4 = core_peek(arena, r10, 8)?; r5 = 1u64; r6 = 63u64; r7 = r1 & r6; r8 = (r5 as i64).wrapping_shl((r7 as u32) & 63) as u64; r9 = r4 | r8; r10 = r3; r3 = u64::MAX; r11 = r9; r9 = u64::MAX; core_poke(arena, r10, r11, 8)?; r3 = 0; 
return Ok(r3);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f51(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r12 = r0; r13 = r1; r2 = f48(arena, &[r12, r13])?; r12 = r2; r3 = f41(arena, &[r12])?; r12 = r2; r4 = f41(arena, &[r12])?; r12 = r4; r4 = u64::MAX; r4 = core_peek(arena, r12, 8)?; r5 = 18446744073709551615u64; r6 = 1u64; r7 = 63u64; r8 = r1 & r7; r9 = (r6 as i64).wrapping_shl((r8 as u32) & 63) as u64; r10 = (r5 as i64).wrapping_sub(r9 as i64) as u64; r11 = r4 & r10; r12 = r3; r3 = u64::MAX; r13 = r11; r11 = u64::MAX; core_poke(arena, r12, r13, 8)?; r3 = 0; 
return Ok(r3);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f52(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r13 = r1; r2 = f42(arena, &[r13])?; r3 = 0u64; r4 = 0u64; 
'l0: loop {
r5 = if (r3 as i64) < (r2 as i64) { 1 } else { 0 }; 
if r5 == 0 { break 'l0; } else {  }
r6 = 0u64; r7 = 57600u64; r8 = 24u64; r9 = (r0 as i64).wrapping_add(r8 as i64) as u64; r10 = 8u64; r11 = (r3 as i64).wrapping_mul(r10 as i64) as u64; r12 = (r9 as i64).wrapping_add(r11 as i64) as u64; r13 = r12; r12 = u64::MAX; r8 = f41(arena, &[r13])?; r9 = 0u64; r13 = r8; r8 = u64::MAX; r14 = r9; r9 = u64::MAX; core_poke(arena, r13, r14, 8)?; r8 = 0; r3 = (r3 as i64).wrapping_add(1) as u64; r8 = 0u64; r9 = 57601u64; 
continue 'l0;
break 'l0;
}

return Ok(r4);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f53(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r11 = r0; r12 = r1; r2 = f44(arena, &[r11, r12])?; r3 = 0u64; r4 = 0u64; 
'l0: loop {
r5 = if (r3 as i64) < (r1 as i64) { 1 } else { 0 }; 
if r5 == 0 { break 'l0; } else {  }
r6 = 0u64; r7 = 57600u64; r8 = 8u64; r9 = (r3 as i64).wrapping_mul(r8 as i64) as u64; r10 = (r2 as i64).wrapping_add(r9 as i64) as u64; r11 = r10; r10 = u64::MAX; r8 = f41(arena, &[r11])?; r9 = 18446744073709551615u64; r11 = r8; r8 = u64::MAX; r12 = r9; r9 = u64::MAX; core_poke(arena, r11, r12, 8)?; r8 = 0; r3 = (r3 as i64).wrapping_add(1) as u64; r8 = 0u64; r9 = 57601u64; 
continue 'l0;
break 'l0;
}

return Ok(r4);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f54(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r4 = r0; r2 = f41(arena, &[r4])?; r3 = 1u64; r4 = r2; r2 = u64::MAX; r5 = r3; r3 = u64::MAX; core_poke(arena, r4, r5, 4)?; r2 = 0; r4 = r0; r5 = r1; r2 = f52(arena, &[r4, r5])?; r4 = r0; r5 = r1; r2 = f53(arena, &[r4, r5])?; 
return Ok(r2);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f55(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    r0 = a[0];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r1 = 0u64; r3 = r1; r1 = f41(arena, &[r3])?; r2 = 32u64; r3 = r1; r1 = u64::MAX; r4 = r2; core_poke(arena, r3, r4, 8)?; r1 = 0; r1 = 8u64; r3 = r1; r1 = f41(arena, &[r3])?; r3 = r1; r1 = u64::MAX; r4 = r0; core_poke(arena, r3, r4, 8)?; r1 = 0; r1 = 16u64; r3 = r1; r1 = f41(arena, &[r3])?; r2 = 0u64; r3 = r1; r1 = u64::MAX; r4 = r2; r2 = u64::MAX; core_poke(arena, r3, r4, 8)?; r1 = 0; 
return Ok(r1);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f56(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    r0 = a[0];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r1 = 0u64; r9 = r1; r1 = f41(arena, &[r9])?; r9 = r1; r1 = u64::MAX; r1 = core_peek(arena, r9, 8)?; r9 = r0; r2 = f43(arena, &[r9])?; r3 = 8u64; r9 = r3; r3 = f41(arena, &[r9])?; r9 = r3; r3 = u64::MAX; r3 = core_peek(arena, r9, 8)?; r4 = (r1 as i64).wrapping_add(r2 as i64) as u64; r5 = if (r4 as i64) > (r3 as i64) { 1 } else { 0 }; 
if r5 == 0 { __lbl = 19; } else { __lbl = 17; }
match __lbl {
17 => {
r6 = 0u64; 
__lbl = 55;
}
19 => {
r7 = (r1 as i64).wrapping_add(4) as u64; r9 = r7; r7 = u64::MAX; r7 = f41(arena, &[r9])?; r8 = 0u64; r9 = r7; r7 = u64::MAX; r10 = r8; r8 = u64::MAX; core_poke(arena, r9, r10, 4)?; r7 = 0; r7 = (r1 as i64).wrapping_add(8) as u64; r9 = r7; r7 = u64::MAX; r7 = f41(arena, &[r9])?; r9 = r7; r7 = u64::MAX; r10 = r0; core_poke(arena, r9, r10, 4)?; r7 = 0; r9 = r1; r10 = r0; r7 = f54(arena, &[r9, r10])?; r7 = 0u64; r9 = r7; r7 = f41(arena, &[r9])?; r8 = (r1 as i64).wrapping_add(r2 as i64) as u64; r9 = r7; r7 = u64::MAX; r10 = r8; r8 = u64::MAX; core_poke(arena, r9, r10, 8)?; r7 = 0; r7 = 0u64; r9 = r1; r10 = r7; r7 = u64::MAX; r7 = f45(arena, &[r9, r10])?; r6 = r7; 
__lbl = 55;
}
_ => {}
}

return Ok(r6);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f57(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    let mut r45: u64 = 0;
    let mut r46: u64 = 0;
    let mut r47: u64 = 0;
    let mut r48: u64 = 0;
    let mut r49: u64 = 0;
    let mut r50: u64 = 0;
    let mut r51: u64 = 0;
    let mut r52: u64 = 0;
    let mut r53: u64 = 0;
    let mut r54: u64 = 0;
    let mut r55: u64 = 0;
    let mut r56: u64 = 0;
    let mut r57: u64 = 0;
    let mut r58: u64 = 0;
    r0 = a[0];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r1 = 0u64; r3 = if (r0 as i64) < (r1 as i64) { 1 } else { 0 }; 
if r3 != 0 { __lbl = 5; } else { __lbl = 3; }
match __lbl {
3 => {
r4 = 268435456u64; r3 = if (r0 as i64) > (r4 as i64) { 1 } else { 0 }; 
__lbl = 5;
}
_ => {}
}

if r3 == 0 { __lbl = 8; } else { __lbl = 6; }
match __lbl {
6 => {
r6 = 0u64; 
__lbl = 103;
}
8 => {
r7 = 18446744073709551615u64; r8 = 16u64; r27 = r8; r8 = f41(arena, &[r27])?; r27 = r8; r8 = u64::MAX; r8 = core_peek(arena, r27, 8)?; r9 = 18446744073709551615u64; r10 = 0u64; 
'l0: loop {
r11 = 0u64; r12 = if (r8 as i64) != (r11 as i64) { 1 } else { 0 }; 
if r12 == 0 { break 'l0; } else {  }
r13 = 0u64; r14 = 57600u64; r15 = 16u64; r16 = (r8 as i64).wrapping_add(r15 as i64) as u64; r27 = r16; r16 = u64::MAX; r15 = f41(arena, &[r27])?; r27 = r15; r15 = u64::MAX; r15 = core_peek(arena, r27, 8)?; r16 = 0u64; r18 = if (r9 as i64) < (r16 as i64) { 1 } else { 0 }; 
if r18 == 0 { __lbl = 40; } else { __lbl = 33; }
match __lbl {
33 => {
r19 = (r8 as i64).wrapping_add(8) as u64; r27 = r19; r19 = u64::MAX; r19 = f41(arena, &[r27])?; r27 = r19; r19 = u64::MAX; r19 = core_peek(arena, r27, 4)?; r18 = if (r19 as i64) == (r0 as i64) { 1 } else { 0 }; 
__lbl = 40;
}
_ => {}
}

if r18 == 0 { __lbl = 68; } else { __lbl = 41; }
match __lbl {
41 => {
r22 = 0u64; r23 = if (r7 as i64) < (r22 as i64) { 1 } else { 0 }; 
if r23 == 0 { __lbl = 54; } else { __lbl = 44; }
match __lbl {
44 => {
r25 = 16u64; r27 = r25; r25 = f41(arena, &[r27])?; r27 = r25; r25 = u64::MAX; r28 = r15; core_poke(arena, r27, r28, 8)?; r25 = 0; r24 = 0u64; 
__lbl = 64;
}
54 => {
r25 = 16u64; r26 = (r7 as i64).wrapping_add(r25 as i64) as u64; r27 = r26; r26 = u64::MAX; r25 = f41(arena, &[r27])?; r27 = r25; r25 = u64::MAX; r28 = r15; core_poke(arena, r27, r28, 8)?; r25 = 0; r24 = 0u64; 
__lbl = 64;
}
_ => {}
}
r9 = r8; r8 = 0u64; r21 = 0u64; 
__lbl = 71;
}
68 => {
r7 = r8; r8 = r15; r21 = 0u64; 
__lbl = 71;
}
_ => {}
}
r22 = 0u64; r23 = 57601u64; 
continue 'l0;
break 'l0;
}
r10 = 0u64; r11 = if (r9 as i64) < (r10 as i64) { 1 } else { 0 }; 
if r11 == 0 { __lbl = 83; } else { __lbl = 78; }
match __lbl {
78 => {
r27 = r0; r13 = f56(arena, &[r27])?; r12 = r13; 
__lbl = 99;
}
83 => {
r27 = r9; r28 = r0; r13 = f54(arena, &[r27, r28])?; r13 = (r9 as i64).wrapping_add(4) as u64; r27 = r13; r13 = u64::MAX; r13 = f41(arena, &[r27])?; r27 = r13; r13 = u64::MAX; r13 = core_peek(arena, r27, 4)?; r27 = r9; r28 = r13; r13 = u64::MAX; r13 = f45(arena, &[r27, r28])?; r12 = r13; 
__lbl = 99;
}
_ => {}
}
r6 = r12; 
__lbl = 103;
}
_ => {}
}

return Ok(r6);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f58(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    let mut r45: u64 = 0;
    let mut r46: u64 = 0;
    r0 = a[0];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r1 = (r0 as i64).wrapping_add(8) as u64; r15 = r1; r1 = u64::MAX; r1 = f41(arena, &[r15])?; r15 = r1; r1 = u64::MAX; r1 = core_peek(arena, r15, 4)?; r2 = 0u64; r3 = 0u64; 
'l0: loop {
r4 = if (r2 as i64) < (r1 as i64) { 1 } else { 0 }; 
if r4 == 0 { break 'l0; } else {  }
r5 = 0u64; r6 = 57600u64; r15 = r0; r16 = r2; r7 = f49(arena, &[r15, r16])?; r8 = 1u64; r9 = if (r7 as i64) == (r8 as i64) { 1 } else { 0 }; 
if r9 == 0 { __lbl = 37; } else { __lbl = 19; }
match __lbl {
19 => {
r15 = r0; r16 = r1; r11 = f44(arena, &[r15, r16])?; r12 = 8u64; r13 = (r2 as i64).wrapping_mul(r12 as i64) as u64; r14 = (r11 as i64).wrapping_add(r13 as i64) as u64; r15 = r14; r14 = u64::MAX; r11 = f41(arena, &[r15])?; r15 = r11; r11 = u64::MAX; r11 = core_peek(arena, r15, 8)?; r15 = r11; r11 = u64::MAX; r11 = f63(arena, &[r15])?; r10 = 0u64; 
__lbl = 38;
}
37 => {
r10 = 0u64; 
__lbl = 38;
}
_ => {}
}
r2 = (r2 as i64).wrapping_add(1) as u64; r7 = 0u64; r8 = 57601u64; 
continue 'l0;
break 'l0;
}
r3 = (r0 as i64).wrapping_add(4) as u64; r15 = r3; r3 = u64::MAX; r3 = f41(arena, &[r15])?; r4 = (r0 as i64).wrapping_add(4) as u64; r15 = r4; r4 = u64::MAX; r4 = f41(arena, &[r15])?; r15 = r4; r4 = u64::MAX; r4 = core_peek(arena, r15, 4)?; r5 = (r4 as i64).wrapping_add(1) as u64; r15 = r3; r3 = u64::MAX; r16 = r5; r5 = u64::MAX; core_poke(arena, r15, r16, 4)?; r3 = 0; r3 = 16u64; r15 = r3; r3 = f41(arena, &[r15])?; r15 = r3; r3 = u64::MAX; r3 = core_peek(arena, r15, 8)?; r4 = 16u64; r5 = (r0 as i64).wrapping_add(r4 as i64) as u64; r15 = r5; r5 = u64::MAX; r4 = f41(arena, &[r15])?; r15 = r4; r4 = u64::MAX; r16 = r3; core_poke(arena, r15, r16, 8)?; r4 = 0; r4 = 16u64; r15 = r4; r4 = f41(arena, &[r15])?; r15 = r4; r4 = u64::MAX; r16 = r0; core_poke(arena, r15, r16, 8)?; r4 = 0; 
return Ok(r4);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f59(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    let mut r45: u64 = 0;
    let mut r46: u64 = 0;
    let mut r47: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r16 = r0; r2 = f47(arena, &[r16])?; r3 = 0u64; r4 = if (r2 as i64) < (r3 as i64) { 1 } else { 0 }; 
if r4 == 0 { __lbl = 7; } else { __lbl = 5; }
match __lbl {
5 => {
r5 = 18446744073709551615u64; 
__lbl = 37;
}
7 => {
r6 = (r2 as i64).wrapping_add(8) as u64; r16 = r6; r6 = u64::MAX; r6 = f41(arena, &[r16])?; r16 = r6; r6 = u64::MAX; r6 = core_peek(arena, r16, 4)?; r7 = 0u64; r9 = if (r1 as i64) < (r7 as i64) { 1 } else { 0 }; 
if r9 != 0 { __lbl = 17; } else { __lbl = 16; }
match __lbl {
16 => {
r9 = if (r1 as i64) >= (r6 as i64) { 1 } else { 0 }; 
__lbl = 17;
}
_ => {}
}

if r9 == 0 { __lbl = 20; } else { __lbl = 18; }
match __lbl {
18 => {
r11 = 18446744073709551615u64; 
__lbl = 34;
}
20 => {
r16 = r2; r17 = r6; r12 = f44(arena, &[r16, r17])?; r13 = 8u64; r14 = (r1 as i64).wrapping_mul(r13 as i64) as u64; r15 = (r12 as i64).wrapping_add(r14 as i64) as u64; r16 = r15; r15 = u64::MAX; r12 = f41(arena, &[r16])?; r16 = r12; r12 = u64::MAX; r12 = core_peek(arena, r16, 8)?; r11 = r12; 
__lbl = 34;
}
_ => {}
}
r5 = r11; 
__lbl = 37;
}
_ => {}
}

return Ok(r5);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f60(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    let mut r45: u64 = 0;
    let mut r46: u64 = 0;
    let mut r47: u64 = 0;
    let mut r48: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    r2 = a[2];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r17 = r0; r3 = f47(arena, &[r17])?; r4 = 0u64; r5 = if (r3 as i64) < (r4 as i64) { 1 } else { 0 }; 
if r5 == 0 { __lbl = 7; } else { __lbl = 5; }
match __lbl {
5 => {
r6 = 18446744073709551615u64; 
__lbl = 41;
}
7 => {
r7 = (r3 as i64).wrapping_add(8) as u64; r17 = r7; r7 = u64::MAX; r7 = f41(arena, &[r17])?; r17 = r7; r7 = u64::MAX; r7 = core_peek(arena, r17, 4)?; r8 = 0u64; r10 = if (r1 as i64) < (r8 as i64) { 1 } else { 0 }; 
if r10 != 0 { __lbl = 17; } else { __lbl = 16; }
match __lbl {
16 => {
r10 = if (r1 as i64) >= (r7 as i64) { 1 } else { 0 }; 
__lbl = 17;
}
_ => {}
}

if r10 == 0 { __lbl = 20; } else { __lbl = 18; }
match __lbl {
18 => {
r12 = 18446744073709551615u64; 
__lbl = 39;
}
20 => {
r17 = r3; r18 = r7; r13 = f44(arena, &[r17, r18])?; r14 = 8u64; r15 = (r1 as i64).wrapping_mul(r14 as i64) as u64; r16 = (r13 as i64).wrapping_add(r15 as i64) as u64; r17 = r16; r16 = u64::MAX; r13 = f41(arena, &[r17])?; r17 = r13; r13 = u64::MAX; r18 = r2; core_poke(arena, r17, r18, 8)?; r13 = 0; r17 = r3; r18 = r1; r13 = f51(arena, &[r17, r18])?; r12 = 0u64; 
__lbl = 39;
}
_ => {}
}
r6 = r12; 
__lbl = 41;
}
_ => {}
}

return Ok(r6);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f61(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    let mut r43: u64 = 0;
    let mut r44: u64 = 0;
    let mut r45: u64 = 0;
    let mut r46: u64 = 0;
    let mut r47: u64 = 0;
    let mut r48: u64 = 0;
    r0 = a[0];
    r1 = a[1];
    r2 = a[2];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r17 = r0; r3 = f47(arena, &[r17])?; r4 = 0u64; r5 = if (r3 as i64) < (r4 as i64) { 1 } else { 0 }; 
if r5 == 0 { __lbl = 7; } else { __lbl = 5; }
match __lbl {
5 => {
r6 = 18446744073709551615u64; 
__lbl = 41;
}
7 => {
r7 = (r3 as i64).wrapping_add(8) as u64; r17 = r7; r7 = u64::MAX; r7 = f41(arena, &[r17])?; r17 = r7; r7 = u64::MAX; r7 = core_peek(arena, r17, 4)?; r8 = 0u64; r10 = if (r1 as i64) < (r8 as i64) { 1 } else { 0 }; 
if r10 != 0 { __lbl = 17; } else { __lbl = 16; }
match __lbl {
16 => {
r10 = if (r1 as i64) >= (r7 as i64) { 1 } else { 0 }; 
__lbl = 17;
}
_ => {}
}

if r10 == 0 { __lbl = 20; } else { __lbl = 18; }
match __lbl {
18 => {
r12 = 18446744073709551615u64; 
__lbl = 39;
}
20 => {
r17 = r3; r18 = r7; r13 = f44(arena, &[r17, r18])?; r14 = 8u64; r15 = (r1 as i64).wrapping_mul(r14 as i64) as u64; r16 = (r13 as i64).wrapping_add(r15 as i64) as u64; r17 = r16; r16 = u64::MAX; r13 = f41(arena, &[r17])?; r17 = r13; r13 = u64::MAX; r18 = r2; core_poke(arena, r17, r18, 8)?; r13 = 0; r17 = r3; r18 = r1; r13 = f50(arena, &[r17, r18])?; r12 = 0u64; 
__lbl = 39;
}
_ => {}
}
r6 = r12; 
__lbl = 41;
}
_ => {}
}

return Ok(r6);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f62(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    r0 = a[0];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r8 = r0; r1 = f47(arena, &[r8])?; r2 = 0u64; r3 = if (r1 as i64) < (r2 as i64) { 1 } else { 0 }; 
if r3 == 0 { __lbl = 7; } else { __lbl = 5; }
match __lbl {
5 => {
r4 = 18446744073709551615u64; 
__lbl = 22;
}
7 => {
r8 = r1; r5 = f41(arena, &[r8])?; r8 = r1; r6 = f41(arena, &[r8])?; r8 = r6; r6 = u64::MAX; r6 = core_peek(arena, r8, 4)?; r7 = (r6 as i64).wrapping_add(1) as u64; r8 = r5; r5 = u64::MAX; r9 = r7; r7 = u64::MAX; core_poke(arena, r8, r9, 4)?; r5 = 0; r4 = 0u64; 
__lbl = 22;
}
_ => {}
}

return Ok(r4);
    #[allow(unreachable_code)] { return Ok(r0); }
}
fn f63(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {
    let mut r0: u64 = 0;
    let mut r1: u64 = 0;
    let mut r2: u64 = 0;
    let mut r3: u64 = 0;
    let mut r4: u64 = 0;
    let mut r5: u64 = 0;
    let mut r6: u64 = 0;
    let mut r7: u64 = 0;
    let mut r8: u64 = 0;
    let mut r9: u64 = 0;
    let mut r10: u64 = 0;
    let mut r11: u64 = 0;
    let mut r12: u64 = 0;
    let mut r13: u64 = 0;
    let mut r14: u64 = 0;
    let mut r15: u64 = 0;
    let mut r16: u64 = 0;
    let mut r17: u64 = 0;
    let mut r18: u64 = 0;
    let mut r19: u64 = 0;
    let mut r20: u64 = 0;
    let mut r21: u64 = 0;
    let mut r22: u64 = 0;
    let mut r23: u64 = 0;
    let mut r24: u64 = 0;
    let mut r25: u64 = 0;
    let mut r26: u64 = 0;
    let mut r27: u64 = 0;
    let mut r28: u64 = 0;
    let mut r29: u64 = 0;
    let mut r30: u64 = 0;
    let mut r31: u64 = 0;
    let mut r32: u64 = 0;
    let mut r33: u64 = 0;
    let mut r34: u64 = 0;
    let mut r35: u64 = 0;
    let mut r36: u64 = 0;
    let mut r37: u64 = 0;
    let mut r38: u64 = 0;
    let mut r39: u64 = 0;
    let mut r40: u64 = 0;
    let mut r41: u64 = 0;
    let mut r42: u64 = 0;
    r0 = a[0];
    let mut __lbl: usize = 0; let _ = &mut __lbl;
r11 = r0; r1 = f47(arena, &[r11])?; r2 = 0u64; r3 = if (r1 as i64) < (r2 as i64) { 1 } else { 0 }; 
if r3 == 0 { __lbl = 7; } else { __lbl = 5; }
match __lbl {
5 => {
r4 = 18446744073709551615u64; 
__lbl = 31;
}
7 => {
r11 = r1; r5 = f41(arena, &[r11])?; r11 = r5; r5 = u64::MAX; r5 = core_peek(arena, r11, 4)?; r6 = (r5 as i64).wrapping_sub(1) as u64; r11 = r1; r7 = f41(arena, &[r11])?; r11 = r7; r7 = u64::MAX; r12 = r6; core_poke(arena, r11, r12, 4)?; r7 = 0; r7 = 0u64; r8 = if (r6 as i64) == (r7 as i64) { 1 } else { 0 }; 
if r8 == 0 { __lbl = 29; } else { __lbl = 24; }
match __lbl {
24 => {
r11 = r1; r10 = f58(arena, &[r11])?; r9 = 1u64; 
__lbl = 30;
}
29 => {
r9 = 0u64; 
__lbl = 30;
}
_ => {}
}
r4 = r9; 
__lbl = 31;
}
_ => {}
}

return Ok(r4);
    #[allow(unreachable_code)] { return Ok(r0); }
}
pub fn core_init(arena: &mut [u8], a0: u64) -> Result<u64, &'static str> { f55(arena, &[a0]) }
pub fn alloc(arena: &mut [u8], a0: u64) -> Result<u64, &'static str> { f57(arena, &[a0]) }
pub fn cell_get(arena: &mut [u8], a0: u64, a1: u64) -> Result<u64, &'static str> { f59(arena, &[a0, a1]) }
pub fn cell_set(arena: &mut [u8], a0: u64, a1: u64, a2: u64) -> Result<u64, &'static str> { f60(arena, &[a0, a1, a2]) }
pub fn cell_set_child(arena: &mut [u8], a0: u64, a1: u64, a2: u64) -> Result<u64, &'static str> { f61(arena, &[a0, a1, a2]) }
pub fn rc_inc(arena: &mut [u8], a0: u64) -> Result<u64, &'static str> { f62(arena, &[a0]) }
pub fn rc_dec(arena: &mut [u8], a0: u64) -> Result<u64, &'static str> { f63(arena, &[a0]) }
