use polka::{BytecodeChunk, Chunk, Module, OpCode, Register};
use std::fmt::Write;

use crate::TranspileError;

// AOT backend for `<core>` runtime libraries (heap/RC/region written in abrase).
// A core module has no VM: functions operate only on scalar registers plus a
// flat byte arena via the peek/poke/ptr_add/arena_base intrinsics. Emit each fn
// as `f{idx}(arena, args) -> u64`, inline the intrinsics with the L2 bounds and
// alignment checks, and expose every `pub fn` as a raw-ABI wrapper.

fn reg(r: Register) -> String { format!("r{}", r.0) }

fn target(i: usize, off: i16) -> isize { i as isize + 1 + off as isize }

fn intrinsic_name(module: &Module, fn_id: usize) -> Option<&str> {
    match module.functions.get(fn_id) {
        Some(Chunk::Native(n)) => Some(n.name.as_str()),
        _ => None,
    }
}

// no_std: only `&[u8]` slices, core ops, and `&'static str` errors — no alloc,
// no std. Suitable for linking as `libmyriad-core` on bare metal.
const PRELUDE: &str = r#"
fn core_peek(arena: &[u8], addr: u64, width: u64) -> Result<u64, &'static str> {
    if addr & (width - 1) != 0 { return Err("core: misaligned access"); }
    let end = match addr.checked_add(width) { Some(e) => e, None => return Err("core: address overflow") };
    if end > arena.len() as u64 { return Err("core: out-of-bounds access"); }
    let mut v: u64 = 0;
    let mut i = 0u64;
    while i < width { v |= (arena[(addr + i) as usize] as u64) << (8 * i); i += 1; }
    Ok(v)
}
fn core_poke(arena: &mut [u8], addr: u64, val: u64, width: u64) -> Result<(), &'static str> {
    if addr & (width - 1) != 0 { return Err("core: misaligned access"); }
    let end = match addr.checked_add(width) { Some(e) => e, None => return Err("core: address overflow") };
    if end > arena.len() as u64 { return Err("core: out-of-bounds access"); }
    let mut i = 0u64;
    while i < width { arena[(addr + i) as usize] = (val >> (8 * i)) as u8; i += 1; }
    Ok(())
}
"#;

pub fn transpile_core(module: &Module) -> Result<String, TranspileError> {
    let mut out = String::new();
    out.push_str("// generated by polka-rustc (core backend)\n");
    out.push_str(PRELUDE);

    let param_counts: Vec<usize> = module.functions.iter().map(|c| c.param_count()).collect();

    // `__module_init` sets up the VM module-table (device ops); a core lib has no
    // module table, so skip it. Core consts must be inlined as PushConst.
    let init_id = module.exports.iter()
        .find(|e| e.name == "__module_init").map(|e| e.fn_id as usize);

    for (idx, chunk) in module.functions.iter().enumerate() {
        if Some(idx) == init_id { continue; }
        if let Chunk::Bytecode(bc) = chunk {
            emit_core_fn(&mut out, idx, bc, &param_counts, module)?;
        }
    }

    for export in &module.exports {
        if export.name == "__module_init" || export.name == "main" { continue; }
        let fid = export.fn_id as usize;
        let k = param_counts.get(fid).copied().unwrap_or(0);
        let params: Vec<String> = (0..k).map(|j| format!("a{}: u64", j)).collect();
        let args: Vec<String> = (0..k).map(|j| format!("a{}", j)).collect();
        let _ = write!(
            out,
            "pub fn {}(arena: &mut [u8]{}{}) -> Result<u64, &'static str> {{ f{}(arena, &[{}]) }}\n",
            export.name,
            if k == 0 { "" } else { ", " },
            params.join(", "),
            fid,
            args.join(", "),
        );
    }

    Ok(out)
}

fn emit_core_fn(
    out: &mut String,
    idx: usize,
    bc: &BytecodeChunk,
    param_counts: &[usize],
    module: &Module,
) -> Result<(), TranspileError> {
    let _ = write!(out, "fn f{}(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {{\n", idx);
    let nregs = bc.reg_count + crate::STAGE_SLACK;
    for r in 0..nregs {
        let _ = write!(out, "    let mut r{}: u64 = 0;\n", r);
    }
    for j in 0..param_counts[idx] {
        let _ = write!(out, "    r{} = a[{}];\n", j, j);
    }
    out.push_str("    let mut pc: usize = 0;\n    loop { match pc {\n");

    for (i, op) in bc.code.iter().enumerate() {
        let next = i as isize + 1;
        let stmt = emit_core_op(i, op, next, bc.reg_count, param_counts, module, &bc.constants, bc.code.len())?;
        let _ = write!(out, "        {} => {{ {} }}\n", i, stmt);
    }
    out.push_str("        _ => return Ok(r0),\n    } }\n}\n");
    Ok(())
}

fn set(d: Register, expr: String, next: isize) -> String {
    format!("{} = {}; pc = {};", reg(d), expr, next)
}

fn emit_core_op(
    i: usize,
    op: &OpCode,
    next: isize,
    reg_count: usize,
    param_counts: &[usize],
    module: &Module,
    constants: &[u64],
    len: usize,
) -> Result<String, TranspileError> {
    let bin = |a: Register, b: Register, m: &str| format!("({} as i64).{}({} as i64) as u64", reg(a), m, reg(b));
    let cmp = |a: Register, b: Register, o: &str| format!("if ({} as i64) {} ({} as i64) {{ 1 }} else {{ 0 }}", reg(a), o, reg(b));
    let s = match op {
        OpCode::Add(d, a, b) => set(*d, bin(*a, *b, "wrapping_add"), next),
        OpCode::Sub(d, a, b) => set(*d, bin(*a, *b, "wrapping_sub"), next),
        OpCode::Mul(d, a, b) => set(*d, bin(*a, *b, "wrapping_mul"), next),
        OpCode::Div(d, a, b) => format!("{} = match ({} as i64).checked_div({} as i64) {{ Some(v) => v as u64, None => return Err(\"div by zero\") }}; pc = {};", reg(*d), reg(*a), reg(*b), next),
        OpCode::Mod(d, a, b) => format!("{} = match ({} as i64).checked_rem({} as i64) {{ Some(v) => v as u64, None => return Err(\"mod by zero\") }}; pc = {};", reg(*d), reg(*a), reg(*b), next),
        OpCode::Neg(d, a) => set(*d, format!("({} as i64).wrapping_neg() as u64", reg(*a)), next),
        OpCode::AddImm(d, a, imm) => set(*d, format!("({} as i64).wrapping_add({}) as u64", reg(*a), *imm as i64), next),
        OpCode::SubImm(d, a, imm) => set(*d, format!("({} as i64).wrapping_sub({}) as u64", reg(*a), *imm as i64), next),
        OpCode::Eq(d, a, b) => set(*d, cmp(*a, *b, "=="), next),
        OpCode::Neq(d, a, b) => set(*d, cmp(*a, *b, "!="), next),
        OpCode::Lt(d, a, b) => set(*d, cmp(*a, *b, "<"), next),
        OpCode::Gt(d, a, b) => set(*d, cmp(*a, *b, ">"), next),
        OpCode::Lte(d, a, b) => set(*d, cmp(*a, *b, "<="), next),
        OpCode::Gte(d, a, b) => set(*d, cmp(*a, *b, ">="), next),
        OpCode::And(d, a, b) => set(*d, format!("{} & {}", reg(*a), reg(*b)), next),
        OpCode::Or(d, a, b) => set(*d, format!("{} | {}", reg(*a), reg(*b)), next),
        OpCode::Xor(d, a, b) => set(*d, format!("{} ^ {}", reg(*a), reg(*b)), next),
        OpCode::Shl(d, a, b) => set(*d, format!("({} as i64).wrapping_shl(({} as u32) & 63) as u64", reg(*a), reg(*b)), next),
        OpCode::Shr(d, a, b) => set(*d, format!("({} as i64).wrapping_shr(({} as u32) & 63) as u64", reg(*a), reg(*b)), next),
        OpCode::PushConst(d, ci) => {
            let v = constants.get(*ci as usize).copied().unwrap_or(0);
            set(*d, format!("{}u64", v), next)
        }
        OpCode::Copy(d, a) => set(*d, reg(*a), next),
        OpCode::Move(d, a) => format!("{} = {}; {} = u64::MAX; pc = {};", reg(*d), reg(*a), reg(*a), next),
        OpCode::Jmp(off) => format!("pc = {};", jt(i, *off, len)),
        OpCode::Jz(c, off) => format!("if {} == 0 {{ pc = {}; }} else {{ pc = {}; }}", reg(*c), jt(i, *off, len), next),
        OpCode::Jnz(c, off) => format!("if {} != 0 {{ pc = {}; }} else {{ pc = {}; }}", reg(*c), jt(i, *off, len), next),
        OpCode::Ret(r) => format!("return Ok({});", reg(*r)),
        OpCode::Drop(_) => format!("pc = {};", next),
        // Region push/pop scaffolding around scopes. Core holds no handles, so
        // every region operation is a no-op (nothing to track or reclaim).
        OpCode::Deo(_, _) => format!("pc = {};", next),
        OpCode::Call(dest, fn_id) => {
            let fid = *fn_id as usize;
            let k = *param_counts.get(fid).ok_or_else(|| TranspileError::Unsupported(format!("call to unknown fn {}", fid)))?;
            let args: Vec<String> = (0..k).map(|j| reg(Register((reg_count + j) as u8))).collect();
            if let Some(name) = intrinsic_name(module, fid) {
                emit_intrinsic(*dest, name, &args, next)?
            } else {
                format!("{} = f{}(arena, &[{}])?; pc = {};", reg(*dest), fid, args.join(", "), next)
            }
        }
        other => return Err(TranspileError::Unsupported(format!("core op {:?}", other))),
    };
    Ok(s)
}

fn jt(i: usize, off: i16, len: usize) -> String {
    let t = target(i, off);
    if t < 0 || t > len as isize { "usize::MAX".to_string() } else { format!("{}", t) }
}

fn emit_intrinsic(dest: Register, name: &str, args: &[String], next: isize) -> Result<String, TranspileError> {
    let d = reg(dest);
    let s = match name {
        "__peek8" => format!("{} = core_peek(arena, {}, 1)?; pc = {};", d, args[0], next),
        "__peek32" => format!("{} = core_peek(arena, {}, 4)?; pc = {};", d, args[0], next),
        "__peek64" => format!("{} = core_peek(arena, {}, 8)?; pc = {};", d, args[0], next),
        "__poke8" => format!("core_poke(arena, {}, {}, 1)?; {} = 0; pc = {};", args[0], args[1], d, next),
        "__poke32" => format!("core_poke(arena, {}, {}, 4)?; {} = 0; pc = {};", args[0], args[1], d, next),
        "__poke64" => format!("core_poke(arena, {}, {}, 8)?; {} = 0; pc = {};", args[0], args[1], d, next),
        "__ptr_add" => format!("{} = {}.wrapping_add({}); pc = {};", d, args[0], args[1], next),
        "__arena_base" => format!("{} = 0; pc = {};", d, next),
        other => return Err(TranspileError::Unsupported(format!("core intrinsic {}", other))),
    };
    Ok(s)
}
