use polka::{BytecodeChunk, Chunk, Module, OpCode, Register};
use std::fmt::Write;

use crate::TranspileError;

// AOT backend for `<core>` runtime libraries (heap/RC/region written in abrase).
// A core module has no VM: functions operate only on scalar registers plus a
// flat byte arena via the peek/poke/ptr_add/arena_base intrinsics. Emit each fn
// as `f{idx}(arena, args) -> u64`, inline the intrinsics with the L2 bounds and
// alignment checks, and expose every `pub fn` as a raw-ABI wrapper.

fn reg(r: Register) -> String { format!("r{}", r.0) }

fn target(i: usize, off: i16) -> isize { i as isize + 1 + off as isize }

fn intrinsic_name(module: &Module, fn_id: usize) -> Option<&str> {
    match module.functions.get(fn_id) {
        Some(Chunk::Native(n)) => Some(n.name.as_str()),
        _ => None,
    }
}

// no_std: only `&[u8]` slices, core ops, and `&'static str` errors — no alloc,
// no std. Suitable for linking as `libmyriad-core` on bare metal.
const PRELUDE: &str = r#"
fn core_peek(arena: &[u8], addr: u64, width: u64) -> Result<u64, &'static str> {
    if addr & (width - 1) != 0 { return Err("core: misaligned access"); }
    let end = match addr.checked_add(width) { Some(e) => e, None => return Err("core: address overflow") };
    if end > arena.len() as u64 { return Err("core: out-of-bounds access"); }
    let mut v: u64 = 0;
    let mut i = 0u64;
    while i < width { v |= (arena[(addr + i) as usize] as u64) << (8 * i); i += 1; }
    Ok(v)
}
fn core_poke(arena: &mut [u8], addr: u64, val: u64, width: u64) -> Result<(), &'static str> {
    if addr & (width - 1) != 0 { return Err("core: misaligned access"); }
    let end = match addr.checked_add(width) { Some(e) => e, None => return Err("core: address overflow") };
    if end > arena.len() as u64 { return Err("core: out-of-bounds access"); }
    let mut i = 0u64;
    while i < width { arena[(addr + i) as usize] = (val >> (8 * i)) as u8; i += 1; }
    Ok(())
}
"#;

pub fn transpile_core(module: &Module) -> Result<String, TranspileError> {
    let mut out = String::new();
    out.push_str("// generated by polka-rustc (core backend)\n");
    out.push_str(PRELUDE);

    let param_counts: Vec<usize> = module.functions.iter().map(|c| c.param_count()).collect();

    // `__module_init` sets up the VM module-table (device ops); a core lib has no
    // module table, so skip it. Core consts must be inlined as PushConst.
    let init_id = module.exports.iter()
        .find(|e| e.name == "__module_init").map(|e| e.fn_id as usize);

    for (idx, chunk) in module.functions.iter().enumerate() {
        if Some(idx) == init_id { continue; }
        if let Chunk::Bytecode(bc) = chunk {
            emit_core_fn(&mut out, idx, bc, &param_counts, module)?;
        }
    }

    for export in &module.exports {
        if export.name == "__module_init" || export.name == "main" { continue; }
        let fid = export.fn_id as usize;
        let k = param_counts.get(fid).copied().unwrap_or(0);
        let params: Vec<String> = (0..k).map(|j| format!("a{}: u64", j)).collect();
        let args: Vec<String> = (0..k).map(|j| format!("a{}", j)).collect();
        let _ = write!(
            out,
            "pub fn {}(arena: &mut [u8]{}{}) -> Result<u64, &'static str> {{ f{}(arena, &[{}]) }}\n",
            export.name,
            if k == 0 { "" } else { ", " },
            params.join(", "),
            fid,
            args.join(", "),
        );
    }

    Ok(out)
}

use std::collections::{BTreeMap, BTreeSet};

enum Term { Goto(usize), Br { cond: String, t: usize, f: usize }, Ret(String) }
struct CBlock { body: String, term: Term }

fn term_succ(t: &Term) -> Vec<usize> {
    match t { Term::Goto(a) => vec![*a], Term::Br { t, f, .. } => vec![*t, *f], Term::Ret(_) => vec![] }
}

fn emit_core_fn(out: &mut String, idx: usize, bc: &BytecodeChunk, param_counts: &[usize], module: &Module) -> Result<(), TranspileError> {
    let _ = write!(out, "fn f{}(arena: &mut [u8], a: &[u64]) -> Result<u64, &'static str> {{\n", idx);
    let nregs = bc.reg_count + crate::STAGE_SLACK;
    for r in 0..nregs { let _ = write!(out, "    let mut r{}: u64 = 0;\n", r); }
    for j in 0..param_counts[idx] { let _ = write!(out, "    r{} = a[{}];\n", j, j); }
    out.push_str("    let mut __lbl: usize = 0; let _ = &mut __lbl;\n");

    let len = bc.code.len();
    let leaders = crate::block_leaders(&bc.code, None);
    let block_ids: Vec<usize> = (0..len).filter(|&i| leaders[i]).collect();
    let block_ids = if block_ids.is_empty() { vec![0] } else { block_ids };

    let mut blocks: BTreeMap<usize, CBlock> = BTreeMap::new();
    for (bi, &start) in block_ids.iter().enumerate() {
        let end = block_ids.get(bi + 1).copied().unwrap_or(len);
        let mut body = String::new();
        let mut term = Term::Goto(end);
        let mut body_end = end;
        if end > start {
            match &bc.code[end - 1] {
                OpCode::Jmp(off) => { term = Term::Goto(jtgt(end - 1, *off, len)); body_end = end - 1; }
                OpCode::Jz(c, off) => { term = Term::Br { cond: format!("r{} == 0", c.0), t: jtgt(end - 1, *off, len), f: end }; body_end = end - 1; }
                OpCode::Jnz(c, off) => { term = Term::Br { cond: format!("r{} != 0", c.0), t: jtgt(end - 1, *off, len), f: end }; body_end = end - 1; }
                OpCode::Ret(r) => { term = Term::Ret(reg(*r)); body_end = end - 1; }
                _ => {}
            }
        }
        for j in start..body_end {
            let s = emit_core_op(&bc.code[j], bc.reg_count, param_counts, module, &bc.constants)?;
            if !s.is_empty() { body.push_str(&s); body.push(' '); }
        }
        if let Term::Goto(t) = term { if t >= len { term = Term::Ret("r0".into()); } }
        blocks.insert(start, CBlock { body, term });
    }

    let mut rl = Reloop { blocks: &blocks, lbl: 0 };
    let all: BTreeSet<usize> = block_ids.iter().cloned().collect();
    let mut entry = BTreeSet::new();
    entry.insert(block_ids[0]);
    rl.process(&entry, &all, out, &BTreeMap::new());
    out.push_str("    #[allow(unreachable_code)] { return Ok(r0); }\n}\n");
    Ok(())
}

fn jtgt(i: usize, off: i16, len: usize) -> usize {
    let t = target(i, off);
    if t < 0 { len } else { t as usize }
}

// Relooper: reducible CFG -> structured Rust. `breaks` maps a target reached from
// an enclosing scope to its continue/break statement; such edges are excluded
// from the local CFG so loop bodies become acyclic and recursion terminates.
struct Reloop<'a> { blocks: &'a BTreeMap<usize, CBlock>, lbl: usize }

impl<'a> Reloop<'a> {
    fn lsucc(&self, b: usize, breaks: &BTreeMap<usize, String>) -> Vec<usize> {
        term_succ(&self.blocks[&b].term).into_iter().filter(|s| !breaks.contains_key(s)).collect()
    }
    fn forward(&self, entries: &BTreeSet<usize>, set: &BTreeSet<usize>, breaks: &BTreeMap<usize, String>) -> BTreeSet<usize> {
        let mut seen = BTreeSet::new();
        let mut stk: Vec<usize> = entries.iter().cloned().filter(|e| set.contains(e)).collect();
        while let Some(b) = stk.pop() {
            if !seen.insert(b) { continue; }
            for s in self.lsucc(b, breaks) { if set.contains(&s) { stk.push(s); } }
        }
        seen
    }
    fn coreach(&self, targets: &BTreeSet<usize>, set: &BTreeSet<usize>, breaks: &BTreeMap<usize, String>) -> BTreeSet<usize> {
        let mut res: BTreeSet<usize> = targets.iter().cloned().filter(|t| set.contains(t)).collect();
        let mut changed = true;
        while changed {
            changed = false;
            for &b in set {
                if res.contains(&b) { continue; }
                if self.lsucc(b, breaks).iter().any(|s| res.contains(s)) { res.insert(b); changed = true; }
            }
        }
        res
    }
    fn jump_to(&self, t: usize, ne: &BTreeSet<usize>, breaks: &BTreeMap<usize, String>) -> String {
        if let Some(s) = breaks.get(&t) { format!("{};", s) }
        else if ne.contains(&t) { if ne.len() == 1 { String::new() } else { format!("__lbl = {};", t) } }
        else { String::new() }
    }
    fn emit_term(&self, b: usize, ne: &BTreeSet<usize>, breaks: &BTreeMap<usize, String>, out: &mut String) {
        match &self.blocks[&b].term {
            Term::Ret(e) => { let _ = write!(out, "return Ok({});\n", e); }
            Term::Goto(t) => { let j = self.jump_to(*t, ne, breaks); if !j.is_empty() { out.push_str(&j); out.push('\n'); } }
            Term::Br { cond, t, f } => {
                let jt = self.jump_to(*t, ne, breaks);
                let jf = self.jump_to(*f, ne, breaks);
                if !(jt.is_empty() && jf.is_empty()) { let _ = write!(out, "if {} {{ {} }} else {{ {} }}\n", cond, jt, jf); }
            }
        }
    }
    fn process(&mut self, entries: &BTreeSet<usize>, set: &BTreeSet<usize>, out: &mut String, breaks: &BTreeMap<usize, String>) {
        if entries.is_empty() { return; }
        let reach = self.forward(entries, set, breaks);
        if reach.is_empty() { return; }
        let has_back = entries.iter().any(|&e| {
            let succ: BTreeSet<usize> = self.lsucc(e, breaks).into_iter().filter(|s| reach.contains(s)).collect();
            self.forward(&succ, &reach, breaks).contains(&e)
        });
        if has_back {
            let mut inner = self.coreach(entries, &reach, breaks);
            for &e in entries { inner.insert(e); }
            let next: BTreeSet<usize> = reach.difference(&inner).cloned().collect();
            let next_entries: BTreeSet<usize> = inner.iter().flat_map(|&b| self.lsucc(b, breaks)).filter(|s| next.contains(s)).collect();
            let id = self.lbl; self.lbl += 1;
            let mut ib = breaks.clone();
            for &e in entries { ib.insert(e, format!("continue 'l{}", id)); }
            for &n in &next_entries { ib.insert(n, format!("break 'l{}", id)); }
            let _ = write!(out, "'l{}: loop {{\n", id);
            self.process(entries, &inner, out, &ib);
            let _ = write!(out, "break 'l{};\n}}\n", id);
            self.process(&next_entries, &next, out, breaks);
            return;
        }
        if entries.len() == 1 {
            let e = *entries.iter().next().unwrap();
            out.push_str(&self.blocks[&e].body); out.push('\n');
            let rest: BTreeSet<usize> = reach.iter().filter(|&&b| b != e).cloned().collect();
            let ne: BTreeSet<usize> = self.lsucc(e, breaks).into_iter().filter(|s| rest.contains(s)).collect();
            self.emit_term(e, &ne, breaks, out);
            self.process(&ne, &rest, out, breaks);
            return;
        }
        // Only handle entries that no other entry can reach; entries reachable
        // from a sibling flow through `next` (after the dispatch), never as a
        // sibling arm (the `match` runs once, so a late `__lbl` set is missed).
        let mut next_entries: BTreeSet<usize> = BTreeSet::new();
        let mut owned_all: BTreeSet<usize> = BTreeSet::new();
        let mut regions: Vec<(usize, BTreeSet<usize>)> = Vec::new();
        for &e in entries {
            let others: BTreeSet<usize> = entries.iter().cloned().filter(|&x| x != e).collect();
            let from_others = self.forward(&others, &reach, breaks);
            if from_others.contains(&e) { next_entries.insert(e); continue; }
            let mut es = BTreeSet::new(); es.insert(e);
            let owned: BTreeSet<usize> = self.forward(&es, &reach, breaks).into_iter().filter(|b| !from_others.contains(b) || *b == e).collect();
            for &b in &owned { owned_all.insert(b); }
            regions.push((e, owned));
        }
        let _ = write!(out, "match __lbl {{\n");
        for (e, owned) in regions {
            let _ = write!(out, "{} => {{\n", e);
            let exits: BTreeSet<usize> = owned.iter().flat_map(|&b| self.lsucc(b, breaks)).filter(|s| !owned.contains(s) && reach.contains(s)).collect();
            for &x in &exits { next_entries.insert(x); }
            let mut mb = breaks.clone();
            for &x in &exits { mb.insert(x, format!("__lbl = {}", x)); }
            let mut sub = BTreeSet::new(); sub.insert(e);
            self.process(&sub, &owned, out, &mb);
            out.push_str("}\n");
        }
        out.push_str("_ => {}\n}\n");
        let next: BTreeSet<usize> = reach.difference(&owned_all).cloned().collect();
        self.process(&next_entries, &next, out, breaks);
    }
}

fn emit_core_op(op: &OpCode, reg_count: usize, param_counts: &[usize], module: &Module, constants: &[u64]) -> Result<String, TranspileError> {
    let bin = |a: Register, b: Register, m: &str| format!("({} as i64).{}({} as i64) as u64", reg(a), m, reg(b));
    let cmp = |a: Register, b: Register, o: &str| format!("if ({} as i64) {} ({} as i64) {{ 1 }} else {{ 0 }}", reg(a), o, reg(b));
    let asg = |d: Register, e: String| format!("{} = {};", reg(d), e);
    let s = match op {
        OpCode::Add(d, a, b) => asg(*d, bin(*a, *b, "wrapping_add")),
        OpCode::Sub(d, a, b) => asg(*d, bin(*a, *b, "wrapping_sub")),
        OpCode::Mul(d, a, b) => asg(*d, bin(*a, *b, "wrapping_mul")),
        OpCode::Div(d, a, b) => format!("{} = match ({} as i64).checked_div({} as i64) {{ Some(v) => v as u64, None => return Err(\"div by zero\") }};", reg(*d), reg(*a), reg(*b)),
        OpCode::Mod(d, a, b) => format!("{} = match ({} as i64).checked_rem({} as i64) {{ Some(v) => v as u64, None => return Err(\"mod by zero\") }};", reg(*d), reg(*a), reg(*b)),
        OpCode::Neg(d, a) => asg(*d, format!("({} as i64).wrapping_neg() as u64", reg(*a))),
        OpCode::AddImm(d, a, imm) => asg(*d, format!("({} as i64).wrapping_add({}) as u64", reg(*a), *imm as i64)),
        OpCode::SubImm(d, a, imm) => asg(*d, format!("({} as i64).wrapping_sub({}) as u64", reg(*a), *imm as i64)),
        OpCode::Eq(d, a, b) => asg(*d, cmp(*a, *b, "==")),
        OpCode::Neq(d, a, b) => asg(*d, cmp(*a, *b, "!=")),
        OpCode::Lt(d, a, b) => asg(*d, cmp(*a, *b, "<")),
        OpCode::Gt(d, a, b) => asg(*d, cmp(*a, *b, ">")),
        OpCode::Lte(d, a, b) => asg(*d, cmp(*a, *b, "<=")),
        OpCode::Gte(d, a, b) => asg(*d, cmp(*a, *b, ">=")),
        OpCode::And(d, a, b) => asg(*d, format!("{} & {}", reg(*a), reg(*b))),
        OpCode::Or(d, a, b) => asg(*d, format!("{} | {}", reg(*a), reg(*b))),
        OpCode::Xor(d, a, b) => asg(*d, format!("{} ^ {}", reg(*a), reg(*b))),
        OpCode::Shl(d, a, b) => asg(*d, format!("({} as i64).wrapping_shl(({} as u32) & 63) as u64", reg(*a), reg(*b))),
        OpCode::Shr(d, a, b) => asg(*d, format!("({} as i64).wrapping_shr(({} as u32) & 63) as u64", reg(*a), reg(*b))),
        OpCode::PushConst(d, ci) => asg(*d, format!("{}u64", constants.get(*ci as usize).copied().unwrap_or(0))),
        OpCode::Copy(d, a) => asg(*d, reg(*a)),
        OpCode::Move(d, a) => format!("{} = {}; {} = u64::MAX;", reg(*d), reg(*a), reg(*a)),
        OpCode::Drop(_) | OpCode::Deo(_, _) => String::new(),
        OpCode::Call(dest, fn_id) => {
            let fid = *fn_id as usize;
            let k = *param_counts.get(fid).ok_or_else(|| TranspileError::Unsupported(format!("call to unknown fn {}", fid)))?;
            let args: Vec<String> = (0..k).map(|j| reg(Register((reg_count + j) as u8))).collect();
            if let Some(name) = intrinsic_name(module, fid) { emit_intrinsic(*dest, name, &args)? }
            else { format!("{} = f{}(arena, &[{}])?;", reg(*dest), fid, args.join(", ")) }
        }
        OpCode::Jmp(_) | OpCode::Jz(_, _) | OpCode::Jnz(_, _) | OpCode::Ret(_) => String::new(),
        other => return Err(TranspileError::Unsupported(format!("core op {:?}", other))),
    };
    Ok(s)
}

fn emit_intrinsic(dest: Register, name: &str, args: &[String]) -> Result<String, TranspileError> {
    let d = reg(dest);
    let s = match name {
        "__peek8" => format!("{} = core_peek(arena, {}, 1)?;", d, args[0]),
        "__peek32" => format!("{} = core_peek(arena, {}, 4)?;", d, args[0]),
        "__peek64" => format!("{} = core_peek(arena, {}, 8)?;", d, args[0]),
        "__poke8" => format!("core_poke(arena, {}, {}, 1)?; {} = 0;", args[0], args[1], d),
        "__poke32" => format!("core_poke(arena, {}, {}, 4)?; {} = 0;", args[0], args[1], d),
        "__poke64" => format!("core_poke(arena, {}, {}, 8)?; {} = 0;", args[0], args[1], d),
        "__ptr_add" => format!("{} = {}.wrapping_add({});", d, args[0], args[1]),
        "__arena_base" => format!("{} = 0;", d),
        other => return Err(TranspileError::Unsupported(format!("core intrinsic {}", other))),
    };
    Ok(s)
}

